### ISSUE TITLE
0.76 → 0.77 Regression on hppa - timer-6.5 test fails

### ISSUE THREAD

**Issue by OdyX** [msteveb/jimtcl#102]
Bug-Debian: https://bugs.debian.org/873048

The 0.77 upload to Debian has revealed that this version has regressed on the `hppa` architecture, see https://buildd.debian.org/status/logs.php?pkg=jimtcl&arch=hppa 
```
  timer-6.5 ERR Tcl_AfterCmd procedure, ms argument
  At      : timer.test:192
  Expected: 'before after'
  Got     : 'after after'
  
        timer.test: Total    44   Passed    43  Skipped     0  Failed     1
  ------------------------------------------------------------
  FAILED: 1
  	timer.test:192	timer-6.5
  [...]
  =========================================================================
            Totals: Total  4722   Passed  4502  Skipped   219  Failed     1
```
As Aaron highlighted:
> I'm not sure if this error stemmed from a random glitch or a
consistent problem, but either way tests should consistently
*succeed*. ;-)  Could you please take a look?

I'm happy to help getting that fixed (I can get access to `hppa` developer machines) if you have patches.

**Comment by msteveb** [comment]
Thanks for the report. This test has a tight timing requirement (20ms) that could fail on heavily loaded machine (perhaps a virtual machine). Since the test is essentially identical to timer-6.4, it can simply be removed. I have done that in master.

**Comment by OdyX** [comment]
Great; thank you. It worked: [hppa build log](https://buildd.debian.org/status/fetch.php?pkg=jimtcl&arch=hppa&ver=0.77-2&stamp=1503861277&raw=0)
