### ISSUE TITLE
exec2-3.2 fails on OpenBSD

### ISSUE THREAD

**Issue by aryler** [msteveb/jimtcl#105]
SIGPIPE doesn't seem to happen.

**Comment by msteveb** [comment]
Thanks. That's useful to know. I'll investigate and decided if this test is useful/valid or not.

**Comment by msteveb** [comment]
What version are you running? I just tried OpenBSD 6.2 (amd64) running in VirtualBox and it works every time.

**Comment by aryler** [comment]
Test fails for me on OpenBSD-current (2017/11/01), amd64 and i386.

**Comment by msteveb** [comment]
Sorry, I still can't reproduce it. I tried snapshots/amd64 with the same behaviour. So you'll need to help me out. Can you run something similar to the following?

`strace /bin/cat </dev/urandom | false`

Do you see something that looks like this:

```
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f65dc4584b0}, {SIG_DFL, [], 0}, 8) = 0
write(1, ""..., 4096) = -1 EPIPE (Broken pipe)
+++ exited with 0 +++

```
Or more like this:

```
write(1, ""..., 131072) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=4436, si_uid=1000} ---
+++ killed by SIGPIPE +++
```

**Comment by aryler** [comment]
I don't have strace. Maybe this is helpful?
```
$ ktrace /bin/cat /dev/urandom | false
$ kdump -f ktrace.out
...
cat      CALL  write(1,0xbf4929cb000,0x4000)
cat      PSIG  SIGPIPE SIG_DFL
```

**Comment by msteveb** [comment]
Can you try changing the write to be larger than the pipe size (of 16K or 64K)?

So:

`set bigstring [string repeat a 100000]`

**Comment by aryler** [comment]
That works!
