### ISSUE TITLE
Ideas for how to improve working with byte strings in UTF-8 builds of Jim Tcl

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#106]
Jim Tcl's built-in support for Unicode is a very useful feature and sets it apart from other embedded interpreters like pre-5.3 Lua. However, enabling UTF-8 means that commands like `string index` will operate on characters and not bytes, so the user has to choose between UTF-8 and being able to handle byte strings as easily as in "big" Tcl. I don't know how much this limitation affects other users of Jim Tcl, but it has caused me some problems, most noticeably when I was writing a [JPEG decoder](https://github.com/dbohdan/ptjd). I am opening this issue as a place to aggregate and discuss the possible ways to improve Jim's ability to handle both byte and UTF-8 strings in the same build.

I see three major ways to do it, each with its own drawbacks:
1. Make strings work [like in Tcl 8.x](https://wiki.tcl.tk/1180) (downsides: the required effort, new core code, changes to the internal representation, harder to make optional — seems like a no-go);
2. Add commands to escape and unescape binary data [as suggested in README.utf-8](https://github.com/msteveb/jimtcl/blob/4be55f10c4d2071f493b9a1b60197c5e20f3203d/README.utf-8#L111) (downside: the user will have to keep track of escaping and unescaping data);
3. Add new specialized subcommands, e.g., `string byteindex` and `string byterange` like `string bytelength` (downside: different from Tcl 8.x and feels ad hoc).

What do you think?

**Comment by msteveb** [comment]
I definitely don't like (1) and despite the fact that I wrote it in README.utf-8, I don't much like (2) either.
So that leaves (3) which I think is very reasonable.

We already have `string bytelength` and `string byterange`. Possibly the only thing missing is `string byteindex` (although it can be written in terms of `string byterange`).

The other thing that exists is `pack` and `unpack`. This is an efficient way to access binary data. Is it sufficient?

```
. set a ABC
ABC
. unpack $a -intbe 8 8
66
. unpack $a -str 8 8
B
```

**Comment by dbohdan** [comment]
I was aware of `pack`/`unpack`, but somehow missed that `string byterange` was already a thing. Since this means option (3) is implemented (nice! :-)), I can close the issue. My one suggestion is to update the "Working with Binary Data" section of README.utf-8 to point out the existence of the `string byte*` commands and recommend them instead of (2).

**Comment by msteveb** [comment]
I've updated README.utf-8

**Comment by dbohdan** [comment]
👍
