### ISSUE TITLE
exec2-3.2 fails on Windows (MSYS2)

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#107]
exec2-3.2 now fails for MSYS2 builds on Windows. According to <https://ci.appveyor.com/project/msteveb/jimtcl/history>, the branch **master** started to fail after 88d693ab412c65004bce5cb20c28b3c4a60d1f29.

```none
exec2-3.2 ERR close pipeline return value
At      : exec2.test:55
Expected: '1 {child killed*} CHILDKILLED SIGPIPE'
Got     : '1 {child process exited abnormally} CHILDSTATUS 1'
```

**Comment by msteveb** [comment]
I know, but I can't reproduce it. If someone can reproduce it, that would be helpful

**Comment by msteveb** [comment]
I've given up on this since I can't reproduce it on any other system. This one test is now omitted on systems with MSYSTEM=MING32
