### ISSUE TITLE
Choose better doc format

### ISSUE THREAD

**Issue by aryler** [msteveb/jimtcl#109]
Hi! This audacious request is because asciidoc is needed to build the Jim docs.

On OpenBSD this makes the port pull in asciidoc + a bunch of dependencies and it's slow to generate the docs.
Could you please change the docs to another format?

As I said, this is an audacious request and I don't expect you to change your doc format just because I don't like it so much but this was easier to do at this moment than sending an email. :D

**Comment by msteveb** [comment]
Does anyone have any specific suggestions?

Can't you make the OpenBSD port build without the docs and just point here for the docs?
http://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html

**Comment by krytarowski** [comment]
If this is a dependency.. just add a package option.

If there would be really need to rewrite it, the standard option is to go for groff/mandoc(mdocml).

**Comment by msteveb** [comment]
I'm going to close this ticket. I'll consider a pull request if it doesn't make it harder to write documentation, but writing the documentation is a lot of work so I'm not going to change format unless either someone else does the work or there is a pressing need.
