### ISSUE TITLE
Allow passing a NULL msg to Jim_WrongNumArgs

### ISSUE THREAD

**Issue by aryler** [msteveb/jimtcl#112]
Untested!
```
--- jim.c.orig  Wed Jun  6 16:05:13 2018
+++ jim.c       Wed Jun  6 16:05:27 2018
@@ -11183,7 +11183,7 @@ void Jim_WrongNumArgs(Jim_Interp *interp, int argc, Ji
 
     listObjPtr = Jim_NewListObj(interp, argv, argc);
 
-    if (*msg) {
+    if (msg && *msg) {
         Jim_ListAppendElement(interp, listObjPtr, Jim_NewStringObj(interp, msg, -1));
     }
     Jim_IncrRefCount(listObjPtr);
```

**Comment by msteveb** [comment]
Why?

**Comment by aryler** [comment]
- When there's nothing to say.
- Line up behaviour a bit with Tcl (saves an #ifdef in Tcl/Jim compatible code).
- NULL is smaller than "", since "" requires a pointer and a '\0'   ?

**Comment by aryler** [comment]
You can see what I mean here:
http://chiselapp.com/user/stwo/repository/tjpledge/artifact?ln=100-106&name=ea0b14db3caccd06

**Comment by msteveb** [comment]
OK. The consistency argument is convincing. Done.
