### ISSUE TITLE
Binary download

### ISSUE THREAD

**Issue by svnpenn** [msteveb/jimtcl#113]
Do you have compiled versions available

**Comment by msteveb** [comment]
There are travis and appveyor builds. e.g. https://ci.appveyor.com/project/msteveb/jimtcl/build/0.77.0.141 and https://travis-ci.org/msteveb/jimtcl/builds/389462353?utm_source=github_status&utm_medium=notification

Otherwise, building Jim is very easy. e.g.

$ ./configure --full
$ make

**Comment by svnpenn** [comment]
@msteveb thanks - couple of points

1. i dont see that the travis builds have any artifacts to download

2. the appveyor build does have an artifact to download - perhaps the appveyor project should be linked here http://github.com/msteveb/jimtcl/blob/master/README
