### ISSUE TITLE
Link to mailing list archive is broken

### ISSUE THREAD

**Issue by rdiez** [msteveb/jimtcl#115]
Hi there:

I wanted to ask a question in the mailing list, and I noticed that the "Jim-devel Archives" link is broken.

The page with the broken link is:

http://jim.tcl.tk:8080/cgi-bin/mailman/listinfo/jim-devel

I am reporting it here, because I do not really know whether the mailing list is working.

Thanks,
  rdiez

**Comment by msteveb** [comment]
Thanks for the report. I'll see if I can git it fixed. As far as I know the mailing list is still working.

**Comment by msteveb** [comment]
For some reason the list archives are now private. I don't have access to fix that, but at least they are accessible. The list page now points to the right place: http://sqlite.org:8080/cgi-bin/mailman/private/jim-devel/ and you can view them if you login.
