### ISSUE TITLE
[package require Tcl 8.6] fails

### ISSUE THREAD

**Issue by tangentsoft** [msteveb/jimtcl#116]
According to [the docs](http://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html#_package), the Jim version of `package require` is supposed to support an optional version number, but it fails with

    Error: wrong # args: should be "package cmd pkg"

I got as far as seeing that this has something to do with `proc package` not declaring its optional arity correctly, but my Tcl fu is not strong enough to provide a patch.

My immediate need is to check for compatibility with a particular version of Tcl, but this may affect other packages.

That then begs the question, what version of Tcl should Jim claim to be equivalent to? There are elements from Tcl 8.6 (e.g. `lmap`), but there are also many things in 8.6 that Jim either doesn't support statically or which may be compiled out in the current build (e.g. `file normalize`).

**Comment by msteveb** [comment]
I don't see that behaviour:

```
Welcome to Jim version 0.78
. package provide abc 1.0
. package require abc 2.0
1.0

```
But it does say: "(The version number is ignored)."

Version numbers aren't used in Jim Tcl packages. Simply embed the version in the name.

Regarding your actual problem, Jim shouldn't claim to be equivalent to any version of Tcl.
Use $tcl_platform(engine) and/or test for specific features. e.g. if {"normalize" in [file -commands]} ...

**Comment by tangentsoft** [comment]
I should have mentioned that I was doing this test with `jimsh0` from `autosetup`, which doesn't have the `package` extension built in, but instead uses what's in `bootstrap.tcl`. So, this is a usability bug in the minimal version of the `package` command only: it should also take an optional version string.

Here's a patch to fix that:

<pre>
Index: bootstrap.tcl
==================================================================
--- bootstrap.tcl
+++ bootstrap.tcl
@@ -1,12 +1,14 @@
 # Minimal support for package require
-# No error on failure since C extensions aren't handled
-proc package {cmd pkg} {
+proc package {cmd pkg {ver ""}} {
 	if {$cmd eq "require"} {
 		foreach path $::auto_path {
 			if {[file exists $path/$pkg.tcl]} {
 				uplevel #0 [list source $path/$pkg.tcl]
 				return
 			}
 		}
-	}
+        puts "Can't load package $pkg."
+	} else {
+        puts "Subcommand $cmd not supported in jimsh0."
+    }
 }
</pre>

This patch does two more things besides add an optional but ignored version number parameter:

1. It prevents this from running without complaint:

        . package require dkfhsladhla

    This then causes `jimsh0` to print "Can't load package readdir." on startup, but that sounds like a separate problem: should `jimsh0` be attempting that in the first place?

2. It emits an error if you give a `package` subcommand that `jimsh0` doesn't support.

**Comment by msteveb** [comment]
Well, jimsh0 doesn't really support the package command at all. It has very minimal "package require" support in order to support running unit tests. You should avoid using it. (e.g. autosetup has it's own 'use' command that does a similar thing). But it doesn't hurt to support additional, ignored args, so I'll change that.
