### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [msteveb/jimtcl#117]
Would you like to add more error handling for return values from functions like the following?
- [fputs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream.") ⇒ [utf8_printf](https://github.com/msteveb/jimtcl/blob/d0c1c9c437d5e8af31e3abaacde64663e8eb68e5/sqlite3/shell.c#L372)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [sb_alloc](https://github.com/msteveb/jimtcl/blob/44d5f64c98d75b4f8f274a06550e7079cf5ddd92/linenoise.c#L149)

**Comment by msteveb** [comment]
Can you explain in more detail what you are proposing?

**Comment by msteveb** [comment]
You will have to be more explicit. Apart from Jim_Alloc() and friends where we specifically don't check for errors (and let the OS/allocator handle out-of-memory conditions), where do you think a return value is ignored that indicates a potential bug?

**Comment by elfring** [comment]
I propose to take another look at the linked two source code places (for example).
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by msteveb** [comment]
Oh, so the original comments were links to the code. It would be helpful if you made that clear.

Your first reference is to sqlite3/shell.c which is imported as-is from sqlite3 (for completeness) and is not used. This will never cause a problem in Jim Tcl!. However if you want, you should raise any issues with that project there.

The second is related to malloc, that I have already covered.

You are welcome to run a static code analysis tool and if you find any actual bugs, let me know.
Even better would be test cases (see regtest.tcl) that demonstrate the bug.

**Comment by elfring** [comment]
How do you think about to avoid that [this software](https://github.com/msteveb/jimtcl/blob/44d5f64c98d75b4f8f274a06550e7079cf5ddd92/linenoise.c#L149 "Update candidate: sb_alloc()") [can depend on undefined behaviour](https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers "Do not dereference null pointers.")?
