### ISSUE TITLE
mathfunc namespace?

### ISSUE THREAD

**Issue by q3cpma** [msteveb/jimtcl#121]
Hello,

sorry for the noob question, but I just started learning TCL and am interested in jimtcl because of its size and speed (in some cases). I'm wondering how to change `set max [tcl::mathfunc::max {*}$list]` to work in jimtcl (tested with 0.78).

**Comment by msteveb** [comment]
Hi, Welcome to jimtcl. There is no integration between expr and tcl::mathfunc, but you can implement your own tcl::mathfunc::max if you want. Here is a simple implementation:

```
proc tcl::mathfunc::max {args} {
    lindex [lsort -integer $args] end
}
```
