### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by cup** [msteveb/jimtcl#123]
1. start `jimsh`

2. press any key, for example `p`

3. Result

~~~
Welcome to Jim version 0.78
. Assertion failed!

Program: D:\Desktop\jimsh\jimsh.exe
File: linenoise-win32.c, Line 195

Expression: current->output

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
~~~

https://ci.appveyor.com/project/msteveb/jimtcl

**Comment by msteveb** [comment]
Thanks. The linenoise optimisation for insert/delete doesn't work on win32 where everything needs to be buffered. I'll update linenoise and bring the update into jimtcl.

**Comment by msteveb** [comment]
Fixed
