### ISSUE TITLE
HTTP package

### ISSUE THREAD

**Issue by cup** [msteveb/jimtcl#125]
Tcl has an HTTP package:

~~~
$ tclsh
% package require http
2.8.12
~~~

https://github.com/tcltk/tcl/blob/master/library/http/http.tcl

but it seems JimTcl does not:

~~~
$ jimsh
Welcome to Jim version 0.78
. package require http
Can't load package http
[error] .
~~~

**Comment by msteveb** [comment]
Yes, Tcl has many more packages than Jim. Jim isn’t trying to match every feature that Tcl has. You could port it if you like. Take a look here for an example of porting dns.tcl. http://jim.tcl.tk/index.html/doc/www/www/articles/no-namespaces-revisited/
