### ISSUE TITLE
SoftFloat support

### ISSUE THREAD

**Issue by krytarowski** [msteveb/jimtcl#126]
I'm trying to get jimtcl functional in a restricted environment.

The first milestone to get there is to add a fallback implementation of floating point operations.

I've reused the code from the Berkeley SoftFloat implementation ( https://github.com/ucb-bar/berkeley-softfloat-3 , BSD-3-clause, kept in a subdir), modified it, reduced to the scope of what is needed in jim, extended with missing features (such as isnan()) and got to pass all the regression tests:

```
          Totals: Total  4761   Passed  4539  Skipped   222  Failed     0
```

I cannot [easily] patch the compiler neither patch the environment to emit soft-float code. I need and want to embed this functionality directly into jimtcl as it will be easier to test in regular userland and predict its behavior in the expected target.

Originally I started with FixedFloats, but the results were not acceptable:

```
. expr 1.2+3.4
4.599990844726
```

I find it much better to get a little bit slower code, but with predictable and appreciated results.

Another option would be to disable floats in the runtime... but we were there with Lua-in-the-NetBSD kernel and at the end of the day it causes more harm than benefit. Debating it is a bit offtopic here, but I intend to get regular runtime compatible with regular userland environment. It's a feature to expect 0...1 results in `rand()`.

In order to continue with my efforts, I intend to upstream everything I got now, as otherwise I will end up with a heavily patched fork.

My code has been patched to contain 0 dependencies on external headers (except `jim.h`) and all the files and types are namespaced with a prefix `jim_`/`jim-`. I need this namespacing as I cannot keep two linker/loader symbols with a shared name and two source files with a shared name with something else (in the worst case I would need to keep renaming it locally).

Before I will submit a pull-request I would like to make clear few things:

 - What is the minimal requirement for building JIMTCL? C99? C89? It looks like currently jimtcl attempts to support pre-c99 environment, however it pick C99 features. I need at least 'long long int' (64-bit integer) support for my SoftFloat fallback. I can either keep the 'long long int' detection around or remove. In my SoftFloat code I require 'long long int'. This is not a real problem for !SoftFloat users as the requirements could be elevated just for !FPU targets. If we would require 'long long int', this would simplify a little bit the existing code. In real life NetBSD and Minix switched their bootstraps to C89+'long long int' environments some years back as there are practically no other ones around (and we receive 0 complains).

- I will keep the MATH functions (`JIM_MATH_FUNCTIONS`) in SoftFloat for now unsupported, implementing them is possible, but I would prefer to reschedule it into future as an option.

- I have added a new header: jim-float.h that implements original float/double and contains a fallback for HAVE_SOFTFLOAT including the SoftFloat header.

I have got the following functions implemented: `jim_double_to_wide`, `jim_double_to_float`, `jim_double_add`, `jim_double_sub`, `jim_double_mul`, `jim_double_div`, `jim_double_eq`, `jim_double_le`, `jim_double_lt`, `jim_double_neq`, `jim_double_ge`, `jim_double_isnan`, `jim_double_isinf` + two functions for the `jim_double` <-> string conversions (I am still pondering about the proper name). I keep two functions for float<->double conversions: `jim_wide_to_float`, `jim_wide_to_double`. I have patched the jim core to reuse these functions directly, instead of operations on float/double types. For obvious reasons there are `jim_double*` functions for all `JIM_MATH_FUNCTIONS` operations.

Questions:

 1. Does it look fine?
 2. Do we need such operations for floats? Right now I need 42 .c files mostly for doubles for the above features. Ideally I would prefer to restrict the float support to the following operations: float<->double and float<->string conversions. Nothing needs performing arithmetics on jim_float in the core and for 3rd party users it would be better to simply translate their types to jim_double, perform needed operations and return back to jim_float if needed.

**Comment by krytarowski** [comment]
```
$ ./configure --help|grep soft
  --softfloat           enable SoftFloat IEEE emulation
```

**Comment by krytarowski** [comment]
- Can the endian detection be switched from a runtime function to a preprocessor macro? Right now my SoftFloat code assumes LE. Picking LE/BE in runtime is possible, but it will be slower than hardcoding one or the other.

**Comment by msteveb** [comment]
I’m away on holiday right now. I’ll take a look and comment after I return

**Comment by krytarowski** [comment]
For the time being, here is my DRAFT code for preview:

https://github.com/krytarowski/jimtcl/commit/b29ddf30a4c70138b992f8edaa011121a3fa66a0

**Comment by krytarowski** [comment]
Looking at other projects it would be reasonable and possible here to avoid `jim_float` and `jim_double` and in the SoftFloat mode use preprocessor `#define float ...` and `#define double ...`. This is bit hackish, but should render cleaner API for the default (current, !SoftFloat) case.

This will be probably more natural for code readers.

**Comment by msteveb** [comment]
The answer to your first query is, indeed, C89 + long long. Although it will work without long long too.

Now the bigger issue. While I'm not opposed to making some small tweaks to support this, there are going to be very few consumers of this support, so I don't want to add this complexity directly. If your soft-float support were a library that could be detected and linked, along with a couple of compiler options/#defines, that would be fine. But currently it is looking quite intrusive.

Tell me why you can't use a toolchain with soft-float support?

**Comment by msteveb** [comment]
Yes, the endian support could be compile time, possibly with a fallback to runtime if not able to detect and compile time. autosetup has cc-check-endian

**Comment by krytarowski** [comment]
It's fine for me to maintain jim_softfloat as a separate object linked into jim, but I need the patches that as proposed to be a part of jim. I have no toolchain softfloat support there.

**Comment by msteveb** [comment]
I understand. But this means that every floating point constant and every floating point operation needs to be handles specially. What is your platform that you don't have softfloat support? It might be worth adding to the toolchain since then you will get benefits in many applications instead of just one.

**Comment by krytarowski** [comment]
I'm going to run jimtcl as a kernel module in NetBSD. There will be similar patches for other jim parts, actually more invasive than softfloat ones.. but softfloat is mandatory to move on. I need this code to keep compiler and cpu independent.

**Comment by krytarowski** [comment]
OK, no interest so I picked another Tcl implementation.

**Comment by msteveb** [comment]
That seems like a good choice. Good luck!
