### ISSUE TITLE
[file tail], [file dirname] handle a trailing slash differently than in Tcl 8.x

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#127]
```sh
> echo 'puts [lmap subcmd {tail dirname} {file $subcmd /foo/bar/baz/}]' > test.tcl
> tclsh test.tcl
baz /foo/bar
> jimsh test.tcl
{} /foo/bar/baz
```

**Comment by msteveb** [comment]
This is true, and could be fixed. But is it even correct?
Look at python:

```
>>> import os;
>>> os.path.dirname("/abc/def")
'/abc'
>>> os.path.dirname("/abc/def/")
'/abc/def'
>>> os.path.split("/abc/def/")
('/abc/def', '')
>>>
```

**Comment by dbohdan** [comment]
It is a matter of convention. For example, Erlang and Elixir do the same thing as Python.  Ruby, mainline Tcl, Jacl/JTcl, and POSIX basename(1)/(3) and dirname(1)/(3) ignore the trailing slash.

I think it makes most sense for Jim to follow the behavior of other Tcl implementations and POSIX (since many Tcl programmers are used to C, shell, and POSIX). Doing otherwise can cause subtle bugs. I noticed this discrepancy when porting a backup script from Tcl 8.6. The script seemed to fully work in Jim with minimal changes, but it backed up the wrong directory.

**Comment by dbohdan** [comment]
>Ruby, mainline Tcl, Jacl/JTcl, and POSIX basename(1)/(3) and dirname(1)/(3) ignore the trailing slash.

And now [so does Picol](https://chiselapp.com/user/dbohdan/repository/picol/info/3a6c10cd6706570c).

**Comment by msteveb** [comment]
It was just an observation. Take a look at current git.

**Comment by dbohdan** [comment]
:+1:
