### ISSUE TITLE
[regexp -start/-indices] uses byte offsets in UTF-8 builds

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#128]
I consider this unexpected behavior. First, README.utf-8 lists `regexp` among the commands that support Unicode. Second, in Tcl 8.6 `-start` and `-indices` refer to characters rather than bytes.

```sh
> echo 'puts [regexp -inline . тест]; puts [regexp -inline -start 1 . тест]' > test.tcl
> tclsh test.tcl 
т
е
> jimsh test.tcl 
т
�
```

I think either the behavior of `regexp -start` and `regexp -indices` should be changed (preferable, since it's compatible with mainline Tcl) or a note should be added about how `regexp` indices work.

**Comment by dbohdan** [comment]
This also applies to `regsub -start`.

**Comment by msteveb** [comment]
Thanks for the report. See git for -start, but regexp -indices a bit more complex. I'll get to it in due course.

**Comment by msteveb** [comment]
Try current git and let me know if you find any problems
