### ISSUE TITLE
Release v0.79

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#129]
Consider making another release soon. It has been over a year since the release of Jim Tcl v0.78. The changes made since have significantly improved Tcl 8.x source compatibility in several areas. (Thank you! It really helps my uses of Jim. For example, my [json.tcl](https://github.com/dbohdan/jimhttp/blob/master/json.tcl) now parses unescaped Unicode strings in UTF-8 builds with no changes to its own source code.)

**Comment by msteveb** [comment]
I agree. I've called for changes on the mailing list and will plan to release in the next month.

**Comment by msteveb** [comment]
Done!

**Comment by dbohdan** [comment]
Great! :tada:
I've published static binaries for amd64, arm32v6, and i386 here: https://github.com/dbohdan/jimsh-static/releases/tag/v2.
