### ISSUE TITLE
Tcl 8.x compat when splitting paths with ~

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#132]
Per the man page, in Tcl 8.x `file split` splits the path `/foo/~bar/baz` into `/ foo ./~bar baz` to prevent tilde substitution later.  I prefer Jim's (lack of) handling of `~`, but I think it is useful for other Tcl implementations to follow this rule simply for compatibility.  For example, a script that passes a path fragment to an external tool through `exec` may expect leading tildes to be escaped this way.

Here are the tests I've written for Picol.
```tcl
test file.25    {file split ~foo}             -> ~foo
test file.26    {file split ~~~foo}           -> ~~~foo
test file.27    {file split /foo/~bar/baz}    -> {/ foo ./~bar baz}
test file.28    {file split /~foo/~bar/~baz}  -> {/ ./~foo ./~bar ./~baz}
test file.29    {file split /foo/~~~bar/baz}  -> {/ foo ./~~~bar baz}
test file.30    {file split ~foo/~bar/baz}    -> {~foo ./~bar baz}
```

**Comment by msteveb** [comment]
I like that Jim doesn’t treat ~ as special. I would prefer not to do this.
exec does use the shell so ~ won’t be expanded anywhere

**Comment by dbohdan** [comment]
As I said, I prefer Jim's lack of `~` expansion, too.  I would really rather it stayed the same.  When talking about how it would be useful for other Tcl implementations "to follow this rule", I meant only the `./` escaping rule in `file split`.   `exec` doesn't expand `~`, but a Tcl script may implicitly rely on something like the `lindex` in `exec tool [lindex [file split /foo/~bar/baz] 2]` returning `./~bar` because `tool` treats `~bar` and `./~bar` differently.

**Comment by msteveb** [comment]
I understand that. There are enough differences between Jim and Tcl that I don't think it's worth it.

**Comment by dbohdan** [comment]
If you'd rather not implement this, I won't insist on it.  This issue is theoretical rather than based on real bugs I have found.

In case someone needs it, here is a pure Tcl implementation of `file split` with `~` escaping.  I may release a version that will be maintained later as part of jimhttp or another open source project.

```tcl
# Copyright (c) 2019 D. Bohdan <http://dbohdan.com/>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# This command doesn't understand Windows volumes and paths or UNC.
proc split-path {path {max 1024}} {
    # Detect and strip leading slashes.
    set absolute [regexp ^/+(.*)$ $path _ path]
    set head [expr {!$absolute}]

    set parts {}

    # We can't use [regexp -indices -start N] here because it will cause
    # problems with Unicode in Jim Tcl 0.78 or earlier.
    while {[regexp {^([^/]+)/+(.*)$} $path _ part path]} {
        if {!$head && [regexp ^~ $part]} {
            set part ./$part
        }
        lappend parts $part

        if {[llength $parts] > $max} {
            error {aborted: path has too many parts}
        }

        set head 0
    }

    if {$path ne {}} {
        if {!$head && [regexp ^~ $path]} {
            set path ./$path
        }
        lappend parts $path
    }

    if {$absolute} {
        set parts [linsert $parts 0 /]
    }

    return $parts
}
```
