### ISSUE TITLE
JimResetHashTable() clears not all the fields.

### ISSUE THREAD

**Issue by kuzminrobin** [msteveb/jimtcl#134]
Would be nice to see a comment (in the code) explaining why `JimResetHashTable()` does not clear the fields `type` and  `privdata` of the `Jim_HashTable` struct (but clears/updates all the other fields).
[Struct](https://github.com/msteveb/jimtcl/blob/master/jim.h#L206),
[`JimResetHashTable()` function](https://github.com/msteveb/jimtcl/blob/master/jim.c#L731).

**Comment by msteveb** [comment]
What do you think is not clear? Can you propose a comment?

**Comment by kuzminrobin** [comment]
From a function named `JimResetHashTable()` I would expect the function to clear (to `0`) _all the fields_ of a structure. But the function clears (to `0`) all the fields _except two_. From the context I fail to understand why those two fields are not cleared (to `0`). That is why I would like to see a comment in the code explaining why those two fields are not cleared (to `0`).
Currently I have the suspicion that those two fields have been added to the structure _later_ (after the function `JimResetHashTable()` has been written), and the programmer who added those two fields has forgotten to add the clean-up of those two fields to the function `JimResetHashTable()`. If that is true then the current situation is a bug.

**Comment by msteveb** [comment]
I see. Hash tables can be reset to empty via `Jim_FreeHashTable()` in which case these
fields need to stay as-is. Otherwise a new hash tables is initialised via `Jim_InitHashTable()`, in case  those two fields are set. It's not a bug.

**Comment by kuzminrobin** [comment]
OK (the comment in the code would be nice to have).

**Comment by msteveb** [comment]
Sure. Done!
