### ISSUE TITLE
[string map] mishandles the null byte

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#137]
```
Welcome to Jim version 0.79
. string map {a b} foo\u0000bar
foo
. string map "oo \u0000" foobar
f
```

Unlike the similar limitation in `regexp`/`regsub`, this doesn't seem to be documented.

**Comment by msteveb** [comment]
Yes, so the problem is Jim_StringCompareLen(). While JimStringCompare() correctly handles nulls, Jim_StringCompareLen() is a bit lazy when it adds support for nocase and assumes that string are null terminated. I'll look into fixing this, but it might be a little while.

**Comment by msteveb** [comment]
Actually, although there is a problem with string map, your examples don't show it. Instead what you are seeing there is jimsh simply printing the result as a null terminated string. The actual returned values are correct.

```
. set x [string map {a b} foo\u0000bar]
foo
. string length $x
7
. puts $x
foobbr
. set y [string map "oo \u0000" foobar]
f
. string length $y
5
. puts $y
fbar
```

**Comment by dbohdan** [comment]
My bad.  Here is a proper test that fails.
```tcl
test string-x.x {string map, null bytes} {
    string map "\u0000afternull #" foo\u0000afternull\u0000123456789bar 
} foo#\u0000123456789bar
```

**Comment by msteveb** [comment]
Try current git

**Comment by dbohdan** [comment]
Resolved.  Thanks!  I've uploaded [new static binaries](https://github.com/dbohdan/jimsh-static/releases/tag/v2-0.79-decb1fb49) to jimsh-static.
