### ISSUE TITLE
jim 0.79 - getaddrinfo() stops working with old uclibc

### ISSUE THREAD

**Issue by citrus-it** [msteveb/jimtcl#139]
I'm upgrading jim to 0.79 in a small embedded uclibc Linux environment (mipsel architecture).

After the upgrade, `socket stream google.com:80` stopped working

```
Welcome to Jim version 0.78
. socket stream google.com:80
::aio.sock10
```

```
Welcome to Jim version 0.79
. socket stream google.com:80
Not a valid address: google.com:80
```

This is due to the change that now passes the port ("80" here) as the second argument to `getaddrinfo()`. Changing this back to NULL solves the problem.

From the man page, this should be working so it is likely to be a problem in the C library from the embedded system, but is there any need to pass the service to getaddrinfo() at all since the result is not used?

Thanks!

**Comment by msteveb** [comment]
The advantage of passing the port separately is that we get non-numeric service names for free (like "http" or "discard"). Seems like a bug in uClibc that was fixed at some point:

```
commit 117a5d673c50335749fd0e1b41d19230db97b143
Author: Natanael Copa <natanael.copa@gmail.com>
Date:   Sun Jun 12 12:09:04 2011 +0000

    getaddrinfo: allow numeric service without any hints

    This appears to correspond to what glibc does and this fixes an
    issue with iptables-1.4.11 with udp and raw port numbers.

    (see http://bugzilla.netfilter.org/show_bug.cgi?id=721)

    This fixes #3841
    https://bugs.busybox.net/show_bug.cgi?id=3841

    Signed-off-by: Natanael Copa <natanael.copa@gmail.com>
    Signed-off-by: Bernhard Reutner-Fischer <rep.dot.nop@gmail.com>
```

Can you patch or upgrade your uClibc?

**Comment by citrus-it** [comment]
Ah, thanks for the explanation, that makes sense.Unfortunately I can't patch uclibc as I don't have the source for the modified version in this embedded system, but I can continue to patch jim-aio.c locally.

**Comment by msteveb** [comment]
I think that's best
