### ISSUE TITLE
[string match] doesn't match after a null character

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#143]
`string match *bar* foo\0bar` returns 0 in Jim Tcl and 1 in Tcl 8.6.

**Comment by msteveb** [comment]
This is a known issue and is probably not worth it to fix. Perhaps needs a doc update though

**Comment by dbohdan** [comment]
I see that this applies to all of glob matching, not just `string match`.  Then the [String Matching](http://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html#_string_matching) section could have a similar note to the section [Jim built-in Regular Expressions](http://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html#_jim_built_in_regular_expressions), which says

>Jim Tcl considers that both patterns and strings end at a null character (\x00)
