### ISSUE TITLE
Regexp input scanner not reset in failed optional group

### ISSUE THREAD

**Issue by dahu** [msteveb/jimtcl#144]
The regexp command:

    regexp -inline {^(?:(-)(?:(\w[\w-]*)\|)?)?(\w[\w-]*)$} -debug

produces different results in Jim vs Tcl.
In Jim:

    -debug - {} ebug

In Tcl:

    -debug - {} debug

Erroneously, the Jim regexp engine is not relinquishing its scan of the "d" when looking for `(?:(\w[\w-]*)\|)?`. Input missing the trailing `\|` should abort this optional group. Correctly, the capture of `(\w[\w-]*)` is empty, but it appears that the input scanner is not reset to the position before the group was attempted, hence the missing "d".

**Comment by msteveb** [comment]
Thanks for the report. Fixed in git.

**Comment by dahu** [comment]
Wonderful. Thank you.
