### ISSUE TITLE
Year 2038 [clock format] problem in 32-bit builds

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#145]
The seconds in `clock format` overflow in `i386` and `arm32v6` builds.

```
> ./jimsh-0.79-decb1fb49f-amd64 -e 'clock format 2177452800'
Sat Jan 01 00:00:00 UTC 2039
> ./jimsh-0.79-decb1fb49f-i386  -e 'clock format 2177452800'
Tue Nov 25 17:31:44 UTC 1902
> ./jimsh-0.79-decb1fb49f-i386  -e 'clock format 2177452800 -format %s'
-2117514496
```

**Comment by msteveb** [comment]
We use time_t as provided by the OS. What do you suggest if time_t is not Y2038-safe?

**Comment by dbohdan** [comment]
I'd suggest adding two things:
* A test in `clock.test` so that the user sees a failing test if their system is not Y2038-compliant.
```
test clock-5.1 {Year 2038 compliance} {
    clock format 2200000000 -format %Y-%m-%dT%H:%M:%S -gmt true
} 2039-09-18T23:06:40
```
* A warning about Y2038 specifically on 32-bit Linux in the `clock` docs.  (Other operating systems like FreeBSD and OpenBSD are no longer affected.  They broke the ABI to fix `time_t`, which Linux doesn't do.)

**Comment by msteveb** [comment]
Done

**Comment by msteveb** [comment]
But the test fails on mingw and thus appveyor builds fail. Does setting USE_64BIT_TIME_T work?

**Comment by dbohdan** [comment]
I have looked into this and found the following.

MinGW-w64, which is the version of MinGW used for the AppVeyor CI, determines the size of `time_t` based on whether `_USE_32BIT_TIME_T` is defined.  Apparently `_mingw.h` does define it by default for 32-bit Windows builds.  The intended workaround is to define `__MINGW_USE_VC2005_COMPAT`, which negates this behavior and has no other effects.  Jim Tcl built with `-D__MINGW_USE_VC2005_COMPAT` passes `clock-5.1`.

You can define `__MINGW_USE_VC2005_COMPAT`, for example, in `CFLAGS` in the makefile after you've run `./configure`.  Is there a way to do it cleanly by passing an argument to Jim Tcl's autosetup script?

**Comment by msteveb** [comment]
Thanks. That sounds good. So I think it is better to to check for 32 bit time_t in auto.def rather than wait until we run the tests. Can we always enable __MINGW_USE_VC2005_COMPAT? Perhaps not since we may be linked against code that doesn't define this. Can provide an option to set to this (maybe enabled by default), or just warn and suggest the user adds CFLAGS=-D __MINGW_USE_VC2005_COMPAT when configuring.

**Comment by msteveb** [comment]
How does this look? https://github.com/msteveb/jimtcl/tree/mingw-y2038

**Comment by dbohdan** [comment]
>So I think it is better to to check for 32 bit time_t in auto.def rather than wait until we run the tests.

I agree.  For the reason you said I wouldn't just always define `__MINGW_USE_VC2005_COMPAT`.  ~If you are willing to implement a new `configure` option that adds `-D__MINGW_USE_VC2005_COMPAT` to `CFLAGS`, I would warn the user about 32-bit `time_t` **and** have that option.~  I didn't know you could pass partial `CFLAGS` to autosetup.  In that case a separate command line option is unnecessary.  Just warning the user with an explanation is enough.  What you've done in`mingw-y2038` looks good!
