### ISSUE TITLE
package require returns wrong version string

### ISSUE THREAD

**Issue by The-Markitecht** [msteveb/jimtcl#146]
This might be a reappearance of #11 ?  The symptom looks similar.  I have not investigated in source.

Symptom:  package require returns wrong version string.  100% rate of occurrence.  In my tests it returns 1.0 no matter what was given to package provide.

Steps to repeat:
Place the following by itself in a new file junk.tcl:
>    package provide junk 6.6

Then in the shell:
>   ./jimsh -e 'package require junk'
>>   1.0

Interp build:
>    git checkout 0.79
>>        commit 0aa0fb4e3a38d38a49de9eb585d93d63a370dcf6 (HEAD, tag: 0.79)
>    make clean && make

System:
>    uname -a
>>    Linux hostname 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

>    lsb_release -a
>>    Description:    Debian GNU/Linux 10 (buster)

**Comment by twinshadow** [comment]
https://github.com/msteveb/jimtcl/blob/8041a06372fa1dbbbf58c404bc98096ea2852a17/jim-package.c#L139-L143

The version string is being overwritten with the default without checking that the result of `JimLoadPackage` calls `package provide` itself.

**Comment by twinshadow** [comment]
Haha, I was wrong. The interpreter command `package provide` automatically sets the version to "1.0".

https://github.com/msteveb/jimtcl/blob/8041a06372fa1dbbbf58c404bc98096ea2852a17/jim-package.c#L166

**Comment by msteveb** [comment]
Sorry about the delay in responding to this. We don't use package versions in Jim Tcl. They are just kept for compatibility but are always 1.0. The idea is to include the version in the package name.

e.g. package require html2

I'll check the docs. Maybe this isn't explained clearly (or at all!)

**Comment by twinshadow** [comment]
> I'll check the docs. Maybe this isn't explained clearly (or at all!)

Referencing http://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html#_package
The command`package require` states that the version is ignored but `package provide` does not claim to ignore the version.

**Comment by msteveb** [comment]
Thanks I will update the docs

**Comment by msteveb** [comment]
done

**Comment by The-Markitecht** [comment]
its presence in the API implies that it's supported.  if not supported, it should be eliminated from the API.
