### ISSUE TITLE
Cosmetic: wrong error string in "cd" command

### ISSUE THREAD

**Issue by sgbeal** [msteveb/jimtcl#150]
Just accidentally came across this:

https://github.com/msteveb/jimtcl/blob/master/jim-file.c#L1078

That should presumably say "cd" rather than "dirname".

**Comment by msteveb** [comment]
Thanks for the report, but...

```
. cd
wrong # args: should be "cd dirname"
```

The command name is determined automatically, so dirname means the argument.

**Comment by sgbeal** [comment]
Aha - i misunderstood it to be the command name and was, when i came across that, looking up the `dirname` command, thus the confusion.
