### ISSUE TITLE
BUG - improper malloc(), should be Jim_Alloc() instead.

### ISSUE THREAD

**Issue by duaneellissd** [msteveb/jimtcl#152]
Located here:

    https://github.com/msteveb/jimtcl/blob/master/jim.c#L9019

Issue description:
    All allocations in JIM should go through "JIM_alloc()" and JIM_free()" 
    This allocation does not.

Detected because I have a custom allocator that I am using for all JIM allocations, during the free process - this allocation was detected as not coming from the custom allocator.

**Comment by msteveb** [comment]
Thanks for finding that. Fixed in git.
