### ISSUE TITLE
clock timezone?

### ISSUE THREAD

**Issue by tlcu** [msteveb/jimtcl#153]
Feel free to close this as `wontfix` if this is not something you want in Jim, but how should we get timezone-related data from `clock`? The user guide and source code don't seem to have any `-timezone` flag like vanilla Tcl. Is working with tzdata outside the scope of Jim?

### jimsh
```
. puts [clock format [clock seconds] -timezone America/New_York]
bad option "-timezone": must be -format, or -gmt
[error] .
```
### tclsh
```
% puts [clock format [clock seconds] -timezone America/New_York]
Sun May 03 07:58:07 EDT 2020
%
```

**Comment by msteveb** [comment]
I think this is outside the scope of Jim Tcl. In order to do this properly you really need a complete timezone database and API, something like pytz (http://pytz.sourceforge.net). Could be an add-on to Jim Tcl, but it doesn't belong in the core.
