### ISSUE TITLE
lsearch syntax error crashes Jim

### ISSUE THREAD

**Issue by dirkf** [msteveb/jimtcl#155]
The following accidental fuzz (missing argument to `lsearch -command`) causes a seg fault, or in different invocation contexts trace/breakpoint, illegal instruction, at least on the build 0.79 (MIPS 32) that I have.
```TCL
proc lremove {var args} {
      upvar $var v
      # some idiot left out $v before $args
      set v [lsearch -all -inline -command [lambda {pat val} {return $($val ni $pat)}] $args]
}
set x { ab cd ef gh }
# crashes Jim
lremove x ef ab
```
Obviously a solution is not to make syntax errors, or perhaps to run the program in an environment with more than 128 MB RAM, but if the same thing happens in general it might indicate a problem in command handling. Generally one would like an interpreter to catch errors rather than terminating, even if a particular underlying syntax error might go undetected.

**Comment by dbohdan** [comment]
I have reproduced the crash on Linux on `armv6l` and `i386`.  On `x86_64` I get
```none
. lremove x ef ab
ef ab
```

**Comment by msteveb** [comment]
Thanks for the report. Fixed.
