### ISSUE TITLE
Feature request: TIP 342: Dict Get With Default

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#167]
Tcl 8.7 will ship with the command `dict getwithdefault` or `dict getdef`, a version `dict get` that returns a default value if the requested key does not exist.  It is already implemented and can be tried in 8.7a3.  This is a long-awaited feature requested by many.  One can expect it to be used pervasively once Tcl 8.7 is the mainstream Tcl 8 release.  It would be good for Jim Tcl to have it for its convenience and to ensure compatibility.

### Resources
* [TIP 342](https://core.tcl-lang.org/tips/doc/trunk/tip/342.md)
* [Tests in Tcl 8](https://github.com/tcltk/tcl/blob/ae744cd1dcee7ecc71e7bcfa6371ec394e26f880/tests/dict.test#L2052)

**Comment by msteveb** [comment]
I agree

**Comment by msteveb** [comment]
Try https://github.com/msteveb/jimtcl/tree/tip342

**Comment by dbohdan** [comment]
Works for me!

**Comment by gromgit** [comment]
:+1: here too.
