### ISSUE TITLE
Release v0.80

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#171]
Once #167, #168, and #169 are resolved, could you tag a new release?  Jim Tcl with 99b7ce9, a major improvement to compatibility, needs a convenient version number.

**Comment by msteveb** [comment]
I agree, we are just about due for a release. I'll merge those shortly and plan for a release in the next few weeks.

**Comment by msteveb** [comment]
It's ready to go as soon as I write some release notes.

**Comment by msteveb** [comment]
0.80 has now been released - see http://jim.tcl.tk/index.html/doc/www/www/articles/jim-release-0-80/

**Comment by dbohdan** [comment]
I've updated my build script and released [static binaries for Jim 0.80](https://github.com/dbohdan/jimsh-static/releases/tag/v3-0.80-fb923fab4f).
