### ISSUE TITLE
Change the error string "?arg...?" to "?arg ...?", to match Tcl.

### ISSUE THREAD

**Issue by aryler** [msteveb/jimtcl#173]
Code that runs with Jim or Tcl currently requires tweaks to tests in order to overcome this difference.
Having the Jim string match Tcl's will remove this burden from tests.

**Comment by msteveb** [comment]
Patch? Also note that there is inconsistency between different versions of Tcl. Matching one version may just mean we don't match on another version.

**Comment by dbohdan** [comment]
Here is how Jim, Tcl 8.5, and Tcl 8.6 handle this.

## Jim Tcl

```
. proc foo {x args} {}; foo
wrong # args: should be "foo x ?arg...?"
```

## Tcl 8.5.9

```
% proc foo {x args} {}; foo
wrong # args: should be "foo x ..."
```

## Tcl 8.6.10

```
% proc foo {x args} {}; foo
wrong # args: should be "foo x ?arg ...?"
```

Jim is currently inconsistent: when you rename `args`, it inserts a space before the `...` in the error message.

```
. proc foo {x {args arg}} {}; foo
wrong # args: should be "foo x ?arg ...?"
```

**Comment by msteveb** [comment]
Sure, looks fine. Right after 0.80.
