### ISSUE TITLE
Make [package provide] return the package version, work more like in Tcl

### ISSUE THREAD

**Issue by aryler** [msteveb/jimtcl#174]
Some people (me) use this as a way to get the version of a loaded package.

package require pkg
puts [package provide pkg]

**Comment by msteveb** [comment]
Why would you not just do this?

  puts [package require pkg]

**Comment by aryler** [comment]
[package require] has the side effect of loading the package.
[package provide] tells if a package is loaded or not, and has no side effects.

**Comment by msteveb** [comment]
So you want to know if a package has been loaded, and if so, what version but you don't want to load it.
Seems odd to me. What is the use case of that?
package names will tell you which packages have been loaded

**Comment by aryler** [comment]
[package names] doesn't do that and doesn't tell versions.

**Comment by msteveb** [comment]
Jim Tcl doesn't have package versions. package names tells you which packages have been loaded.

**Comment by aryler** [comment]
Ok.
