### ISSUE TITLE
Socket tests hang

### ISSUE THREAD

**Issue by aryler** [msteveb/jimtcl#180]
On OpenBSD.

The test suite will hang during socket tests unless socket-2.5 is skipped. 
Even if socket-2.5 is skipped, the test suite will hang at the end, with ~30 dead processes, until ^C'd.
The test suite will run successfully to the end if the files socket.test and ssl.test are removed.

Might be related to the error "0.0.0.0:&lt;port&gt;: connect: Invalid argument"?
I'm this error during tests like socket-1.10 and socket-1.11, and somewhere in ssl.test.

**Comment by msteveb** [comment]
Yes, this approach seems a bit non-portable. Can you test branch openbsd_socket_tests ? (7f4c05a1e76a1141)

**Comment by aryler** [comment]
All socket tests pass on the openbsd_socket_tests branch. Thanks.
