### ISSUE TITLE
lsort produces random order

### ISSUE THREAD

**Issue by The-Markitecht** [msteveb/jimtcl#187]
Jim 0.79 compiled with gcc on Debian 10 amd64:

In the following example, `lsort` produces a seemingly random order instead of the expected (documented) order.  100% repeatable.  Input list and output list are each printed in the example.

Removing `-decreasing` doesn't fix the symptom, it only produces a different random order.

Changing `-index end` to `-index 2` has no impact.  That makes sense since they should be equivalent.

```
set matches [list  \
    [list a b 4]  \
    [list a b 8]  \
    [list a b 16]  \
    [list a b 32]  \
    [list a b 4]  \
    [list a b 64]  \
    [list a b 32]  \
]
foreach mat $matches {
    lassign $mat trk other sc
    puts $sc
}
puts =========================
set matches [lsort -decreasing -index end $matches]
foreach mat $matches {
    lassign $mat trk other sc
    puts $sc
}
```

**Comment by The-Markitecht** [comment]
But tclsh86 also gives a similar result:

8
64
4
4
32
32
16

Is there something wrong with the test case?  I've used -index plenty of times before, and its behavior always made sense before.

**Comment by dbohdan** [comment]
Did you forget `-integer`?

**Comment by The-Markitecht** [comment]
I did indeed.  Thanks @dbohdan !!

Closed.
