### ISSUE TITLE
Allow the user to configure the length of command history

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#191]
The fixed default of 100 commands is probably too low.  It is too low for me.  It would be nice to be able to increase it without recompling Jim.

You can change the Linenoise setting with `linenoiseHistorySetMaxLen(count)`.  The Tcl 8 command that configures the history length is  [`history keep ?count?`](https://www.tcl.tk/man/tcl8.6/TclCmd/history.htm#M11), which returns the current setting if no `count` argument is given to it.

**Comment by msteveb** [comment]
Seems reasonable to me.
How does this look? https://github.com/msteveb/jimtcl/tree/history-keep

**Comment by dbohdan** [comment]
The code looks good, and the feature works for me.  I've just tested it.

```tcl
. set n 1000000; history keep $n; foreach i [range $n] { history add $i }; history save test.tcl
. exec wc -l test.tcl
1000000 test.tcl
. history keep
1000000
. history keep -500
. history keep
1000000
. history keep xyz
expected integer but got "xyz"
```

Tcl 8 generates an error on `history keep` with a negative integer, so that is different.  The difference most likely doesn't matter.

**Comment by dbohdan** [comment]
Thanks for implementing this, and so quickly, too.

**Comment by msteveb** [comment]
You're welcome
