### ISSUE TITLE
OO: comments in class definition

### ISSUE THREAD

**Issue by dirkf** [msteveb/jimtcl#192]
On the lines of TIP-582, should it be possible to write these class definitions with the `oo` package?
```
class foo {
    # an interesting instance var that needs documenting
    wtf "weird initial value"
}
```

```
class foo {
    wtf "weird initial value"   # an interesting instance var that needs documenting
}
```
Eg in the second case with Jim 0.79's `oo.tcl`:
```
. foo classvars
wtf {weird initial value} var that # an needs documenting interesting instance
. 
```
The first style is easy to support with a new line 102 inserted before the current in `oo.tcl` (`# Merge in ... precedence`):
```
        set classvars [regsub -line -all -- {^[[:space:]]*#.*$} $classvars ""]
```

**Comment by msteveb** [comment]
Thanks for the input. I would be cautious about adding something this changes the input from a well defined Tcl dictionary to something that may have unintended consequences.
I would probably rather add 'foo addclassvar'. e.g.

```
# an interesting instance var that needs documenting
foo addclassvar wtf "weird initial value"
```

**Comment by dirkf** [comment]
Thanks, I understand the caution as there are both technical and aesthetic/philosophical issues.

In my analysis, the arguments for allowing comments within expressions to be ignored per TIP-582 applied equally for dict constants. As OO is an area where Jim and traditional TCL already diverge, allowing comments within a dict used to define a class would not be a source of incompatibility. As usual, it would be expected that braces within comments need to be escaped or balanced, although the `regsub` one liner that I posted avoids that.

TIP-401 proposed a general approach to embedded comments using a `{#}` operator (building on `{*}`) but there seems to be have been little enthusiasm for it in the last 8 years, perhaps partly because the resulting code looks a bit weird:
```
class foo {
    {#}"an interesting instance var that needs documenting"
    wtf "weird initial value"
}
```
I see a couple of issues with the otherwise plausible `addclassvar` class method:
* it opens the question, what happens to the instance vars of instances that have already been created (the instance vars currently being bound on object creation)?
* practically, is there a way to modify (vs receive a copy of) the classvars outside `proc class` itself?

Alternatively, how about just stripping any key-value pairs with key `#` (or whatever other choice) from the `classvars` parameter of `proc class`? 
```
class foo {
    # {this syntax is already acceptable but leaves an unwanted # classvar}
    wtf "weird initial value" # {in this case with this default value}
}
```

**Comment by dbohdan** [comment]
You can use a [scripted list](https://wiki.tcl-lang.org/page/Scripted+List) here.

```
class foo [sl {
    # first comment
    wtf "weird initial value"  ;# second comment
}]
```

**Comment by dirkf** [comment]
Thanks, that's true. I previously shied away from this because it implied additional scripts and a class format not directly supported by Jim's OO.

Inspired by your comment I found that the small script on the linked page together with the `commands` script that it uses seemed to run fine in Jim 0.79, at about 50 lines of code.

**Comment by dbohdan** [comment]
You're welcome.  If you have any questions about the license for `commands`, I have clarified that with its two authors for the version included in my [Jimlib](https://gitlab.com/dbohdan/jimlib/).  (The `sl` implementation in Jimlib is my own.)

**Comment by dirkf** [comment]
That anticipated my next query, and the answer is MIT and TCL in for the necessary extracts.

I think this is a good solution.
