### ISSUE TITLE
OO vs implicit namespaces

### ISSUE THREAD

**Issue by dirkf** [msteveb/jimtcl#193]
Are the OO and namespace extensions in Jim meant to work together?

If so, there is an issue in case one declares a class:
```
. class ns::myclass {a 123}
ns::myclass
. set x [ns::myclass]
<reference.<ns__myc>.00000000000000000006>
. $x get a
invalid command name "<reference.<ns__myc>.00000000000000000006>"
[error] .
```
In `oo.tcl`, this invocation of `proc class` defines the constructor and method creator procs for `myclass` as `proc ns::myclass new` and `proc ns::myclass method` respectively. These procs in turn define procs (the object dispatcher, the method template) that don't have an explicit namespace prefix and so inherit the namespace of the enclosing proc. The reference name `$obj` returned by the constructor proc doesn't match the dispatcher name `ns::$obj`, and nothing works. Similarly for method definitions.

Adding a global namespace prefix to the relevant proc definitions is a solution that worked for me: l.45 `proc ::$obj {method args} ...`, l.66 `proc "::$classname $method" $arglist ...`.

**Comment by msteveb** [comment]
Thanks for the report. I think two things are needed.
1. When the reference is created, it needs to be qualified (e.g. `::[ref ...]`)
2. When the class is created, it should use a full qualified name (e.g. `class ::ns::myclass`)

We could do that latter in proc class, using:

`set classname ::[namespace canon $classname]`

But then we need to check to see if namespace is enabled. Perhaps simpler to required the caller to qualify the classname.

**Comment by dirkf** [comment]
The case I was looking at (naïve conversion from TCL) used explicit namespace qualifiers throughout.

I added the global qualifiers to the factory procs, believing that refs are already globally unique and not being quite sure that the routines that deal with refs would handle qualified names. Adding a global qualification to the object ref might achieve the same effect with one change vs two.

The right answer should be one where you can equally define a class
* with an explicit namespace qualifier,
* inside `namespace eval ns {...}`, 
* inside a `proc` that has a namespace,
and have the class behave correctly in each case.

I don't think `if {[exists -command namespace]} {set classname ::[namespace canon $classname]}` would add undue complexity.
