### ISSUE TITLE
Regex bug with backreferences

### ISSUE THREAD

**Issue by mpcjanssen** [msteveb/jimtcl#195]
This is with a jimsh  built with the included regex library

```
Welcome to Jim version 0.80
. regexp -all -inline {(.)\1*} "123112314"
1 1 2 2 311 3 2 2 31 3 4 4
```

This is with jimsh built with the system POSIX regex library:

```
. regexp -all -inline {(.)\1*} "123112314"
1 1 2 2 3 3 11 1 2 2 3 3 1 1 4 4
```

With Tcl 8.6

```
% regexp -all -inline {(.)\1*} "123112314"
1 1 2 2 3 3 11 1 2 2 3 3 1 1 4 4
```

The Jim result seems obviously incorrect as `311` and `31` don't make any sense as matches.

**Comment by msteveb** [comment]
Yes, that's right. backreferences aren't supported with the included regexp library.
As you can see, the `\1` is treated as plain `1`

```
. regexp -all -inline {(.)1*} "123112314"
1 1 2 2 311 3 2 2 31 3 4 4
```
I see the documentation doesn't make this clear, which is definitely something that could be improved.

If you use the POSIX regex library, support for backreferences will be system dependent.
For example, on mac they aren't supported. And you won't get utf-8 support.

**Comment by msteveb** [comment]
BTW, from the regex(7) man page:

>        Back references are a dreadful botch, posing major problems for efficient implementations.  They are also
>        somewhat vaguely defined (does "a\(\(b\)*\2\)*d" match "abbbd"?).  Avoid using them.

**Comment by mpcjanssen** [comment]
@msteveb  Can't say I disagree, but if they are supported they should work properly.

**Comment by mpcjanssen** [comment]
BTW this is not high prio for me.

**Comment by mpcjanssen** [comment]
Sorry I misread your comment. They are not supported at all.

**Comment by msteveb** [comment]
I updated the docs to clarify.
