### ISSUE TITLE
Globbing in Windows

### ISSUE THREAD

**Issue by hzarnani** [msteveb/jimtcl#200]
Hi.  Is this globbing expected to work in Windows?

https://github.com/msteveb/jimtcl/blob/bcd4434161897da5203cdfaef8b2227e15d82c45/autosetup/autosetup#L1226

I can no longer build OpenOCD for Windows since the following commit was included in its jimtcl submodule:

https://github.com/msteveb/jimtcl/commit/88256c9ddad271427153d0cbc3db397345d372e0

The error has to do with `cc-check-inline` not being defined, which fails the configure step.

My debugging pointed to the above-mentioned globbing failing to find jim-misc.tcl.  My workaround is to break up

`foreach file [glob -nocomplain $autosetup(libdir)/*.auto $autosetup(libdir)/*/*.auto]`

into two loops (the latter being a nested one for `*/*.auto`) and use `glob -nocomplain -directory <directory> -- *.auto`.

I see that `autosetup_load_auto_modules` was added 4 years ago in https://github.com/msteveb/jimtcl/commit/31a9f433f06b8cc426d281436a628a5fdd3bf755 and must've been tested with Windows.  Is it possible I have a bad build environment?

**Comment by msteveb** [comment]
Yes it should work. I don't have Windows handy at the moment to test though.
Can you add some trace in just above the glob line to see what glob is returning?

`puts glob=[glob -nocomplain $autosetup(libdir)/*.auto $autosetup(libdir)/*/*.auto]`

**Comment by hzarnani** [comment]
I should've been more specific about my build environment and what I already tried.

In my build environment, there's no pre-installed Tcl shell.  So jimsh0 is bootstraped.

Below is the output for the glob command you recommended:

```
$ git log -n1 --oneline
fb923fa (HEAD, tag: 0.80) build: Support sources with CRNL line endings
$ git diff
diff --git a/autosetup/autosetup b/autosetup/autosetup
index 958287e..79cad90 100755
--- a/autosetup/autosetup
+++ b/autosetup/autosetup
@@ -1223,6 +1223,9 @@ proc autosetup_load_auto_modules {} {
                autosetup_load_module $mod eval $modsource($mod)
        }
        # Now any external auto modules
+puts glob=[glob -nocomplain $autosetup(libdir)/*.auto $autosetup(libdir)/*/*.auto]
+
+
        foreach file [glob -nocomplain $autosetup(libdir)/*.auto $autosetup(libd
ir)/*/*.auto] {
                autosetup_load_module [file tail $file] source $file
        }
$ ./configure.gnu --disable-option-checking '--prefix=/
mingw64'  '--enable-ftdi' '--enable-jlink' 'PKG_CONFIG_PATH=/mingw64/lib/pkgconf
ig:/mingw64/share/pkgconfig' --cache-file=/dev/null --srcdir=.
No installed jimsh or tclsh, building local bootstrap jimsh0
glob=
Host System...x86_64-pc-mingw64
Build System...x86_64-pc-mingw64
C compiler... cc -g -O2
C++ compiler... c++ -g -O2
Build C compiler...cc
Checking for stdlib.h...ok
<snip>
Enabling line editing
auto.def:330: Error: invalid command name "cc-check-inline"
$ 
```

Note:
```
No installed jimsh or tclsh, building local bootstrap jimsh0
glob=
```

To make it more clear:

```
$ ls /c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/*.auto
/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/default.auto
/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/jim-misc.auto
/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/tmake.auto
$ ./autosetup/jimsh0.exe -e 'glob /c/Users/Lab/hzarnani/openocd2/jimtcl/autosetu
p/*.auto'
no files matched glob pattern "/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/*
.auto"
$ ./autosetup/jimsh0.exe -e 'glob -directory /c/Users/Lab/hzarnani/openocd2/jimt
cl/autosetup *.auto'
/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/default.auto /c/Users/Lab/hzarna
ni/openocd2/jimtcl/autosetup/jim-misc.auto /c/Users/Lab/hzarnani/openocd2/jimtcl
/autosetup/tmake.auto
$ 
```

I didn't dig deeper into why my jimsh0 doesn't handle globbing as you'd expect.  I searched for "glob" in jimsh0.c and saw some relevant C as well as Tcl code and of course some Windows-specific code.  But I couldn't pin-point the issue in my cursory look.  It may be in `proc glob.explode`.

Also, I just tried building jimsh0 in another MSYS environment, and that handled globbing just fine.  Since I have a workaround that doesn't require any code modification, I'll just do that for now.  But the point is -- it is possible for jimsh0 to build without any warnings, yet it won't work as expected, and you won't know until `auto.def:330` is hit.  That's not good.

**Comment by msteveb** [comment]
Thanks for more info. Perhaps the problem is that this isn't a real Window pathname:

`/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/*.auto`

What if you cd to /c/Users/Lab/hzarnani/openocd2/jimtcl and do:

`jimsh0.exe -e 'glob autosetup/*.auto'`

Or try c:/Users/Lab/...

**Comment by hzarnani** [comment]
/c/Users/... is a Cygpath.  And it is indeed a valid path:

```
$ file C:/Users/Lab/hzarnani/openocd2/jimtcl/autosetup
C:/Users/Lab/hzarnani/openocd2/jimtcl/autosetup: directory
$ file /c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup
/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup: directory
$ cygpath C:/Users/Lab/hzarnani/openocd2/jimtcl/autosetup
/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup
$ cygpath -w /c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup
C:\Users\Lab\hzarnani\openocd2\jimtcl\autosetup
$ 
```

You're right that `/c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup` is not a Windows pathname though.  But if that matters, why does `glob` accept it when passed as the `-directory` as shown here https://github.com/msteveb/jimtcl/issues/200#issuecomment-843016456?

Anyways, I did try your suggestion:

```
$ pwd
/c/Users/Lab/hzarnani/openocd2/jimtcl
$ autosetup/jimsh0.exe -e 'glob C:/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/*.auto'
C:/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/default.auto C:/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/jim-misc.auto C:/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/tmake.auto
$ autosetup/jimsh0.exe -e 'glob autosetup/*.auto'
autosetup/default.auto autosetup/jim-misc.auto autosetup/tmake.auto
$ 
```

I am baffled as to why only `glob /c/Users/Lab/hzarnani/openocd2/jimtcl/autosetup/*.auto` doesn't work...

**Comment by msteveb** [comment]
So let's try the underlying readdir to see what it understands. Does this work to show entries in that directory?

`jimsh -e 'readdir /c/Users/Lab/hzarnani'`

**Comment by msteveb** [comment]
opendir/readdir are implemented in jim-win32compat.c
Perhaps the need some changes for cygwin. I don’t have a cygwin environment so I can’t do it myself.

**Comment by hzarnani** [comment]
> So let's try the underlying readdir to see what it understands. Does this work to show entries in that directory?
> 
> `jimsh -e 'readdir /c/Users/Lab/hzarnani'`

My apologies for the delay.

I assume you meant jimsh0 since that's the problematic Jim Tcl interpreter in question?  If so, then yes, that does read the directory just fine:

```
# jimtcl/autosetup/jimsh0.exe -e 'readdir /c/Users/Lab/hzarnani'
CMSIS_5 openocd openocd2
# 
```

**Comment by hzarnani** [comment]
> opendir/readdir are implemented in jim-win32compat.c
> Perhaps the need some changes for cygwin. I don’t have a cygwin environment so I can’t do it myself.

At this point, since I have a workaround and the problem really seems to be with a tainted MSYS installation on my machine, I think it's appropriate to close this issue.  If I ever get to the bottom of this and find something of value and relevance for the Jim Tcl build system, I'll share that here.

Thanks!
