### ISSUE TITLE
Feature request: [try ... trap ...]

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#204]
It would be nice if Jim supported Tcl 8.6's [`try ... trap pattern variableList ...`](https://www.tcl-lang.org/man/tcl8.6/TclCmd/try.html).  While fewer built-in errors in Jim generate a unique `-errorcode` than in Tcl 8, I still find it useful for my own custom errors.  Compared to matching the error message with `string match` or `regexp`, for example, it leads to more concise code (no rethrowing with `return` if there is no match).  It leaves you more room to rephrase the error message for human readability.

There is a [pure Tcl implementation](https://gitlab.com/dbohdan/jimlib/-/blob/e8d88b7ef83a02f6062a1be40cc487f89bc5ee7c/jimlib.tcl#L2354) of this construct (a port from Tcllib) in Jimlib.  Errors in Jimlib have a unique hierarchical `-errorcode`, like `JIMLIB FILE LIST-DIR UNKNOWN-SWITCH` in proc `lib::file::list-dir`.  One use case is trapping some but not others to make only some errors fatal in a quick script.  I won't exaggerate and say `try ... trap ...` has made a big difference, but I feel it helps.

**Comment by msteveb** [comment]
Yes, I don’t mind it. Would be compatible with Tcl, so that’s good.

**Comment by msteveb** [comment]
I pushed a branch. Please try it out. Also any feedback on the documentation.

**Comment by dbohdan** [comment]
First off, nice!  I'll make use of this.

The built-in `try` now passes [my tests](https://gitlab.com/dbohdan/jimlib/-/blob/e8d88b7ef83a02f6062a1be40cc487f89bc5ee7c/jimlib.tcl#L3181) for `lib::try` (with the exception of try-1.8, which is due a discrepancy in error messages and is unrelated to `trap`).  Feel free to adopt these tests if you want.

I've commented on the documentation.
