### ISSUE TITLE
Allow building both static and shared library

### ISSUE THREAD

**Issue by nmeum** [msteveb/jimtcl#208]
My current understanding of the jimtcl build system is that it is only possible to build either a shared (using `./configure --shared` or a static library). For distributions which package jimtcl it would be desirable to allow building both at the same time. Some distributions like [Alpine]( https://gitlab.alpinelinux.org/alpine/aports/-/commit/0bb77ff29da6227cd4c324470f0f9a6bbe14bbd7) and [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lang/jimtcl/jimtcl-0.78-r2.ebuild?id=5d9f584a18ca653abff3c8db36c43b23f64f0e68) currently build jimtcl twice, once with and once without `--shared`, for this reason.

**Comment by msteveb** [comment]
I'm going to close this out. I will still accept a patch though if someone wants to implement it.
