### ISSUE TITLE
Missing unversioned symlink for shared library

### ISSUE THREAD

**Issue by dmacks** [msteveb/jimtcl#214]
Building jimtcl-0.81 on OS X 10.13 with `--shared` installs lib/libjim0.81.dylib but pkgconfig/jimtcl.pc publishes `-ljim` to link against it. The bug is that `make install` does not create a libjim.dylib -> libjim0.81.dylib symlink.

**Comment by msteveb** [comment]
Take a look at https://github.com/msteveb/jimtcl/tree/install-libjim-fix-214
Does that work?
