### ISSUE TITLE
SH_SOFULLPATH not working

### ISSUE THREAD

**Issue by dmacks** [msteveb/jimtcl#215]
In cc-shared.tcl, `SH_SOFULLPATH` is documented "Set to 1 if the shared library soname should include the full install path" and my darwin platform (OS X 10.13) is defining that flag. But my resulting libjim.0.81.dylib has install_name of just "libjim.0.81.dylib". The fact that the extension is correct indicates that the .tcl is correctly identifying my platform as darwin, so it seems that the flag is just not working as documented.

**Comment by msteveb** [comment]
Yes, the make-based build system was ignoring this. I pushed a fix on a branch. Does it work for you?
