### ISSUE TITLE
getref behaviour change from 0.79 to 0.81

### ISSUE THREAD

**Issue by prpr19xx** [msteveb/jimtcl#218]
Is this a bug?

```
Welcome to Jim version 0.81
. class x {}
x
. x new
::<reference.<x______>.00000000000000000000>
. getref [x new]
expected reference but got "::<reference.<x______>.00000000000000000002>"
[error] .
```

```
Welcome to Jim version 0.79
. class x {}
x
. x new
<reference.<x______>.00000000000000000000>
. getref [x new]
x
```
This commit changing oo.tcl seems to be the cause:
https://github.com/msteveb/jimtcl/commit/0e541ac9fad7c9eb092dc2b7e4a7a3a66b100021

**Comment by prpr19xx** [comment]
Thanks for the fix.
I think you ought to do the len check before accessing str[0] and str[1] though.

**Comment by msteveb** [comment]
There should be no need to check length first. All strings returned from Jim_GetString() are null terminated.
But I agree that the white space removal is wrong in the qualified case. But why is that even necessary? I assert that it isn't. I pushed a change to the branch to remove the white space check. (15a1851fbe5ebfde44a0c4a13ef95fdda5edd6c8)

**Comment by prpr19xx** [comment]
Tested and works for me. I'll believe your assertion.
