### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by quicknquiet** [msteveb/jimtcl#219]
Trying to build jim on Win7 x86 with TDM-GCC10.3 and having Magicsplat TCL installed.
Getting this:
$ make                                                                                                                          
        MKLDEXT _load-static-exts.c                                                                                             
        CC      _load-static-exts.o                                                                                             
        CC      jim-subcmd.o                                                                                                    
        CC      jim-interactive.o                                                                                               
        CC      jim-format.o                                                                                                    
        CC      jim.o                                                                                                           
jim.c: In function 'JimClock':                                                                                                  
jim.c:701:5: warning: 'gettimeofday' is deprecated [-Wdeprecated-declarations]                                                  
  701 |     gettimeofday(&tv, NULL);                                                                                            
      |     ^~~~~~~~~~~~                                                                                                        
In file included from jim.c:65:                                                                                                 
C:/TDM-GCC-32/include/sys/time.h:106:53: note: declared here                                                                    
  106 | int __cdecl __MINGW_NOTHROW __POSIX_2008_DEPRECATED gettimeofday                                                        
      |                                                     ^~~~~~~~~~~~                                                        
        CC      utf8.o                                                                                                          
        CC      jimregexp.o                                                                                                     
        CC      jimiocompat.o                                                                                                   
jimiocompat.c: In function 'JimProcessPid':                                                                                     
jimiocompat.c:98:12: warning: implicit declaration of function 'GetProcessId'; did you mean 'GetProcessHeap'? [-Wimplicit-functi
on-declaration]                                                                                                                 
   98 |     return GetProcessId(pid);                                                                                           
      |            ^~~~~~~~~~~~                                                                                                 
      |            GetProcessHeap                                                                                               
        CC      linenoise.o                                                                                                     
        CC      jim-win32compat.o                                                                                               
        CC      jim-nosignal.o                                                                                                  
        CC      jim-aio.o                                                                                                       
jim-aio.c: In function 'aio_cmd_stat':                                                                                          
jim-aio.c:1433:16: error: storage size of 'sb' isn't known                                                                      
 1433 |     jim_stat_t sb;                                                                                                      
      |                ^~                                                                                                       
jim-aio.c:1433:16: warning: unused variable 'sb' [-Wunused-variable]                                                            
jim-aio.c:1441:1: warning: control reaches end of non-void function [-Wreturn-type]                                             
 1441 | }                                                                                                                       
      | ^                                                                                                                       
make: *** [jim-aio.o] Error 1

**Comment by msteveb** [comment]
Thanks for the report. I pushed a fix on the branch. Does that work for you?

**Comment by quicknquiet** [comment]
apply.test:  Total   25   Passed    21    Skipped    4    Failed    0
Thank you, Steve!
