### ISSUE TITLE
No way to measure time accurately and reliably

### ISSUE THREAD

**Issue by rdiez** [msteveb/jimtcl#240]
I am using JimTcl with OpenOCD, and I wanted to measure how long some operations take in milliseconds.

I wanted to programmatically generate warnings if certain operations take longer than before, for example, if the scripts have changed, the microcontroller is a different one, or if OpenOCD has been upgraded and something is no longer working as fast as it should.

The trouble is, 'clock' gives you the wallclock, which can change unexpectedly, randomly breaking automated tests, and os.uptime only gives the uptime in seconds.

My Tcl skills are not great. Maybe you can suggest some other way.

In C, a fast, accurate and reliable way to measure time is calling clock_gettime() with CLOCK_MONOTONIC.

**Comment by msteveb** [comment]
Jim follows Tcl here. We would need an extension of some sort (say an option to 'clock') in order to support this. I'll have a think about it.

**Comment by gromgit** [comment]
I'd be hesitant to change `clock`, but `time` certainly deserves a monotonic clock implementation, and also seems to be directly relevant to @rdiez's needs.

**Comment by msteveb** [comment]
And I will probably change 'time' to use this too

**Comment by msteveb** [comment]
https://github.com/msteveb/jimtcl/tree/clock-monotonic

**Comment by rdiez** [comment]
First of all, thanks for your work on this.

I wouldn't switch to monotonic time automatically. That way, the user has no way to know whether monotonic time is available, that is, whether the time returned is actually reliable for measurements.

If the system cannot provide an accurate monotonic time, the user may want to not provide some feature or service, or to issue a warning about possible timing problems (like time deltas becoming negative).

I think that the easiest and most flexible way would be to provide access to the various clock types and let the user deal with any errors, should the requested clock type not be available on the current system.
