### ISSUE TITLE
CRTSCTS: requires _GNU_SOURCE or _BSD_SOURCE

### ISSUE THREAD

**Issue by ptrcnull** [msteveb/jimtcl#256]
excerpt from `termios(3)`:
```
       CRTSCTS
              (not in POSIX) Enable RTS/CTS (hardware) flow control.
              [requires _BSD_SOURCE or _SVID_SOURCE]
```

when building with musl libc, CRTSCTS [needs `_GNU_SOURCE` or `_BSD_SOURCE`][1] for the macro to get defined; otherwise the build fails

[1]: https://elixir.bootlin.com/musl/v1.2.3/source/arch/generic/bits/termios.h#L148

**Comment by ptrcnull** [comment]
https://ariadne.space/2021/12/21/stop-defining-feature-test-macros-in-your-code/ :confused: 

nonetheless, thanks ~

**Comment by msteveb** [comment]
I agree it's not ideal. I think it is like this because there is conflict between some macros on some platforms. Still, if someone wants to clean this up and test on lots of platforms I'd be happy to take a patch.

**Comment by msteveb** [comment]
https://github.com/msteveb/jimtcl/tree/feature-test-macros but needs testing on many more platforms
