### ISSUE TITLE
vi key bindings in jimsh

### ISSUE THREAD

**Issue by vetelko** [msteveb/jimtcl#260]
Hello Steve, everyone
is there a chance that vi editing mode
will be available in jimsh ... sometimes :)

**Comment by msteveb** [comment]
Two options. Someone could add vi mode support to https://github.com/msteveb/linenoise
or you could use readline, either with the readline extension or rlwrap.
From rlprompt.tcl:

```
# In order to automatically have readline-editing features
# put this in your $HOME/.jimrc
#
# if {$jim_interactive} {
#    if {[catch {package require rlprompt}] == 0} {
#       rlprompt.shell
#    }
# }
```

**Comment by msteveb** [comment]
Thanks for letting me know, I'll update the comment in rlprompt.tcl
