### ISSUE TITLE
Jimtcl 0.82 test failed on s390x

### ISSUE THREAD

**Issue by yuzibo** [msteveb/jimtcl#267]
hi,

I have uploaded the 0.82 to Debian again and unfortunately found the test failed on s390x:
```bash
make[3]: Entering directory '/<<PKGBUILDDIR>>/static/tests'
        aio.test: Total    29   Passed    29  Skipped     0  Failed     0
      alias.test: Total    34   Passed    34  Skipped     0  Failed     0
      apply.test: Total    25   Passed    21  Skipped     4  Failed     0
    applyns.test: Total    15   Passed    11  Skipped     4  Failed     0
      array.test: Total    29   Passed    29  Skipped     0  Failed     0
     binary.test: Total   591   Passed   490  Skipped   101  Failed     0
      clock.test: Total    19   Passed    19  Skipped     0  Failed     0
     concat.test: Total    16   Passed    16  Skipped     0  Failed     0
   coverage.test: Total    34   Passed    28  Skipped     6  Failed     0
      debug.test:   --- skipped (command debug)
      defer.test: Total    15   Passed    15  Skipped     0  Failed     0
       dict.test: Total    79   Passed    79  Skipped     0  Failed     0
      dict2.test: Total   212   Passed   207  Skipped     5  Failed     0
   ensemble.test: Total     7   Passed     7  Skipped     0  Failed     0
      error.test: Total     3   Passed     3  Skipped     0  Failed     0
event-11.4 ERR Tcl_VwaitCmd procedure
/<<PKGBUILDDIR>>/tests/event.test:118:Error test failure
Expected: {{} x-done y-done before q-done}
Got     : {{} x-done y-done z-done q-done}

      event.test: Total    22   Passed    20  Skipped     1  Failed     1
```
The build log is [here](https://buildd.debian.org/status/fetch.php?pkg=jimtcl&arch=s390x&ver=0.82-2&stamp=1688746340&raw=0)
Because s390x is Debian released arch, so the regression will effect the package's transition to testing.

BTW, here are [some](https://buildd.debian.org/status/package.php?p=jimtcl&suite=experimental) architectures that also have regression but since they are not released arch will not become blocker.

Any issue please let me know.
Thanks

**Comment by msteveb** [comment]
Thanks for the report. That test can probably bit disabled. It can be a bit fragile on a VM or systems that don't give a good guarantee of timeliness. But some of the other failures are interesting. There are a couple that fail to find cc-check-inline during ./configure. I'd like to know what is causing that. I wonder how I can reproduce

**Comment by yuzibo** [comment]
hi,
If for s390x:
1. 
```bash
sudo sbuild-createchroot --debootstrap=mmdebstrap --arch=s390x \
        --make-sbuild-tarball=/srv/sid-s390x-sbuild.tgz \
        sid /tmp/chroots/sid-s390x-sbuild/ \
        http://ftp.cn.debian.org/debian/
```
(then `vim /etc/schroot/chroot.d/sid-s390x-sbuild-xxxxx` to change to `profile=default`)
2. git clone jimtcl from salsa or here I guess it should work also.
3.  cd jimtcl-src
4. `sudo schroot -c sid-s390x-sbuild` then you have s390x qemu user system. 
(I am not sure gdb is enough or not for that)

For powerpc:
```bash
sudo sbuild-createchroot --debootstrap=mmdebstrap --arch=powerpc  \
       --include=debian-ports-archive-keyring,ca-certificates      \
    --make-sbuild-tarball=/srv/sid-powerpc-sbuild.tgz       \
  sid /tmp/chroots/sid-powerpc-sbuild/     \
    http://ftp.ports.debian.org/debian-ports/
```
Usage is as the same above.

For hppa&sh4, I do not think this is the issue from jintcl itself.

**Comment by msteveb** [comment]
Yes, that test on s390 is intermittent. I ran it continuously and it failed about 1 time in 20.

For powerpc, the problem is that readdir doesn't work in bootstrap jimsh (and so glob doesn't work).
Either need to add a dependency on tclsh or alter autosetup/jimsh.c

```
diff --git a/autosetup/jimsh0.c b/autosetup/jimsh0.c
index 63d4596..20bda44 100644
--- a/autosetup/jimsh0.c
+++ b/autosetup/jimsh0.c
@@ -58,6 +58,7 @@
 #define HAVE_DIRENT_H
 #define HAVE_UNISTD_H
 #define HAVE_UMASK
+#define _FILE_OFFSET_BITS 64
 #endif
 #define JIM_VERSION 78
 #ifndef JIM_WIN32COMPAT_H
```

**Comment by msteveb** [comment]
And in jim-readdir.c, jimautoconf.h needs to be first so that the definition of _FILE_OFFSET_BITS is seen in other headers

**Comment by msteveb** [comment]
I pushed a change to increase those timeouts and also add _FILE_OFFSET_BITS. You will need to cherry-pick some patches

**Comment by yuzibo** [comment]
hi,
yesterday I uploaded the jimtcl 0.82-4 to Debian sid, but unfortunately, one test failed:
```
make[3]: Entering directory '/<<PKGBUILDDIR>>/static/tests'
      ...
      defer.test: Total    15   Passed    15  Skipped     0  Failed     0
       dict.test: Total    79   Passed    79  Skipped     0  Failed     0
      dict2.test: Total   212   Passed   207  Skipped     5  Failed     0
   ensemble.test: Total     7   Passed     7  Skipped     0  Failed     0
      error.test: Total     3   Passed     3  Skipped     0  Failed     0
      event.test: Total    22   Passed    21  Skipped     1  Failed     0
       exec.test: Total    78   Passed    78  Skipped     0  Failed     0
exec2-3.2 ERR close pipeline return value
/<<PKGBUILDDIR>>/tests/exec2.test:77:Error test failure
Expected: rc={ok return} result={1 {child killed*} CHILDKILLED SIGPIPE}
Got     : rc=error result={key "-errorcode" not known in dictionary}

      exec2.test: Total    22   Passed    21  Skipped     0  Failed     1
```
the log is [here](https://buildd.debian.org/status/package.php?p=jimtcl&suite=sid)

In fact, I made lots of efforts to check the test failure was fixed in Debian exp as the issue above. I can confirm that 
the same code(0.82-3) was built fine on Debain [exp](https://buildd.debian.org/status/package.php?p=jimtcl&suite=experimental). So the only problem may be that the dependent package with different version.
But the 0.82-4 was built fine on my local qemu-user on ppc64el with sid repo.

Sorry to disturb you again. Could you have a chance to login a real ppc64el machine to look at the issue?

**Comment by yuzibo** [comment]
```
test exec2-3.2 "close pipeline return value" -constraints {pipe signal nomingw32} -body {
	signal ignore SIGPIPE
	# Write more than 64KB which is maximum size of the pipe buffers
	# on all systems we have seen
	set bigstring [string repeat a 100000]
	set f [open [list |cat << $bigstring]]
	set rc [catch {close $f} msg opts]
	lassign [dict get $opts -errorcode] status pid exitcode
	list $rc $msg $status $exitcode
} -match glob -result {1 {child killed*} CHILDKILLED SIGPIPE}
```

Somebody advices to increase the value, but I am not sure it is okay.

**Comment by yuzibo** [comment]
> hi, yesterday I uploaded the jimtcl 0.82-4 to Debian sid, but unfortunately, one test failed on ppc64el:
> 
> ```
> make[3]: Entering directory '/<<PKGBUILDDIR>>/static/tests'
>       ...
>       defer.test: Total    15   Passed    15  Skipped     0  Failed     0
>        dict.test: Total    79   Passed    79  Skipped     0  Failed     0
>       dict2.test: Total   212   Passed   207  Skipped     5  Failed     0
>    ensemble.test: Total     7   Passed     7  Skipped     0  Failed     0
>       error.test: Total     3   Passed     3  Skipped     0  Failed     0
>       event.test: Total    22   Passed    21  Skipped     1  Failed     0
>        exec.test: Total    78   Passed    78  Skipped     0  Failed     0
> exec2-3.2 ERR close pipeline return value
> /<<PKGBUILDDIR>>/tests/exec2.test:77:Error test failure
> Expected: rc={ok return} result={1 {child killed*} CHILDKILLED SIGPIPE}
> Got     : rc=error result={key "-errorcode" not known in dictionary}
> 
>       exec2.test: Total    22   Passed    21  Skipped     0  Failed     1
> ```
> 
> the log is [here](https://buildd.debian.org/status/package.php?p=jimtcl&suite=sid)
> 
> In fact, I made lots of efforts to check the test failure was fixed in Debian exp as the issue above. I can confirm that the same code(0.82-3) was built fine on Debain [exp](https://buildd.debian.org/status/package.php?p=jimtcl&suite=experimental). So the only problem may be that the dependent package with different version. But the 0.82-4 was built fine on my local qemu-user on ppc64el with sid repo.
> 
> Sorry to disturb you again. Could you have a chance to login a real ppc64el machine to look at the issue?

please ignore it, now the jimtcl can be built on ppc64el:
https://buildd.debian.org/status/logs.php?pkg=jimtcl&arch=ppc64el
thanks.

**Comment by msteveb** [comment]
Thanks, that's good news

**Comment by msteveb** [comment]
I'm not sure what we can do here without access to a live machine. It's not clear to me why this test would sometimes fail on that one architecture.

**Comment by yuzibo** [comment]
Yeah, I have the same issue for me also. I can try one ppc64el portbox for Debian Maintainer but will cost more some time.
