### ISSUE TITLE
tests/Makefile: typo ?

### ISSUE THREAD

**Issue by frgm** [msteveb/jimtcl#28]
$? => 1

for example, with wrong test(s):
```$ make && echo ok```
will be "ok" i.e. `make` returns 0

see: [GNU make manual](https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html#index-_0024_003f)

**Comment by msteveb** [comment]
You'll have to be more explicit. How did you configure? What directory are you running make in?
Works for me:

$ make; echo $?
make: Nothing to be done for `all'.
0

**Comment by msteveb** [comment]
Also, you can comment and ask questions on the mailing list. Probably easier there. See http://jim.tcl.tk:8080/cgi-bin/mailman/listinfo/jim-devel

**Comment by frgm** [comment]
both: under `jimtcl/tests/` with `make`
and: under `jimtcl/` with `make test`
return 0 with failed tests

Is it OK ?

**Comment by msteveb** [comment]
OK. Now I understand. Fix committed. Thanks!
