### ISSUE TITLE
timer-3.2 test failure when building with tcl on osx

### ISSUE THREAD

**Issue by fgaz** [msteveb/jimtcl#282]
When jimtcl is built with tcl on osx, this test fails:

```
timer-3.2 ERR TimerHandlerEventProc procedure: multiple timers
/private/tmp/nix-build-jimtcl-0.82.drv-0/source/tests/timer.test:61:Error test failure
Expected: {80 {80 240} {80 240 400}}
Got     : {80 {80 240 400} {80 240 400}}
```

This does not happen on linux or when bootstrapping with jim.

Initially discovered here: https://github.com/NixOS/nixpkgs/pull/253638#issuecomment-1712580394

**Comment by msteveb** [comment]
Thanks for the report. This is not a bug in JimTcl. It is simply that these timer tests are a bit fragile if running on a VM or an overloaded system. I suggest just disabling timer.test.

BTW, I have some comments on the nixos configuration of JimTcl. Where is the best place to provide that feedback?

**Comment by msteveb** [comment]
See #283 
This may help

**Comment by fgaz** [comment]
Thanks, we'll try applying that patch!

> BTW, I have some comments on the nixos configuration of JimTcl. Where is the best place to provide that feedback?

You can open an issue [here](https://github.com/NixOS/nixpkgs/issues/) and tag me
