### ISSUE TITLE
$(...) vs [expr {...}]

### ISSUE THREAD

**Issue by prpr19xx** [msteveb/jimtcl#285]
The documentation says the two forms of the expr command are identical, yet this happens:
```
. puts $(3-1)
2
. if { 2 == 2 } { puts true }
true
. if { $(3 - 1) == 2 } { puts true }
syntax error in expression: " $(3 - 1) == 2 "
[error] . if { [expr {3 - 1}] == 2 } { puts true }
true
.
```
So clearly they are not identical.
There is a comment around line 9111 in jim.c that says "Don't allow expr sugar in expressions".
Either the code needs fixing to make it work as per the documentation, or the documentation needs something that describes the restrictions of the $(...) format.

**Comment by msteveb** [comment]
That's true. This is to catch the common mistake of not realising e.g. if is already evaluating an expression so we would be nesting an expression in an expression which is unnecessary. It could be explained in the documentation though.

**Comment by prpr19xx** [comment]
I added some comments on 244c744.
