### ISSUE TITLE
segfault in "if string length" in jimsh 0.82

### ISSUE THREAD

**Issue by The-Markitecht** [msteveb/jimtcl#290]
See attached test case.

The case is elaborate, but any attempts to simplify it will avoid the segfault, of course.

The case is an RPC client in Jimsh 0.82.  But to get it to that point you have to run the server also, and it requires mainstream tclsh 8.6, not jim.

To do all that, just run the test.sh inside the attached zipfile.  That segfaults in 100% of attempts for me.

Thanks Steve for maintaining jim so well!!

[jim-082-segfault-spare.zip](https://github.com/msteveb/jimtcl/files/14104109/jim-082-segfault-spare.zip)

**Comment by The-Markitecht** [comment]
This might have something to do with the variable it's using (::rpc_buf) being uninitialized.  That might be the case due to a script bug, but it looks like there should be 1 previous "append" that would have initialized it.  

And/or because it's referenced with a global namespace qualifier.

**Comment by The-Markitecht** [comment]
And/or because there's also an xtrace in effect.  Thanks for that feature by the way!!

**Comment by The-Markitecht** [comment]
Yeah.  Initializing it correctly (an empty string) makes it segfault 3 lines later instead.

**Comment by The-Markitecht** [comment]
Yeah.  That other segfaulting line (if $t >= timeout_ms) should have produced a syntax error in expression (missing $).  And it does that, if you comment out the xtrace, so it stops segfaulting.

This bug might have been added along with the xtrace feature.

**Comment by msteveb** [comment]
Thanks for the report. I see the problem. Try branch xtrace-fix

**Comment by The-Markitecht** [comment]
Yes, that works correctly.  Returns correct error messages and stack traces, and no segfault.  Thanks!
