### ISSUE TITLE
aio hang

### ISSUE THREAD

**Issue by prpr19xx** [msteveb/jimtcl#291]
With ad72004, this produces the expected result:
```
. set f [socket stream www.google.com:80]
::aio.sock4
. $f puts -nonewline "GET / HTTP/1.1\r\n"
. $f puts -nonewline "Host: www.google.com\r\n"
. $f puts -nonewline "Connection: close\r\n"
. $f puts -nonewline "\r\n" 
. $f gets
HTTP/1.1 200 OK
.

```
With 41f431f and subsequent, it just hangs after the "$f gets", without producing any output, until presumably the server times it out and closes the connection.

**Comment by msteveb** [comment]
The socket is fully buffered so your puts typically won't be sent. Either make it line buffered or add '$f flush' after the last puts

**Comment by prpr19xx** [comment]
OK, it's an easy fix, but it breaks previously working code.
I note that the 0.82 release documentation didn't actually state what the default buffering mode was, nor does the current version say this has changed, but at least it now tells you what it is.

**Comment by msteveb** [comment]
The docs for aio buffering say:

    Channels usually begin in full buffering mode, unless they identify
    as a tty channel, in which case line buffering is used, and `stderr`
    begins with no buffering.

And this is still true. With full buffering you can't rely on when the buffer is flushed without an explicit flush. If it worked before it was just "lucky" as a side effect of the implementation (probably that a switch from write to read caused a flush), but that is not part of the documented interface.
