### ISSUE TITLE
UBSan complains while executing Jim_LreplaceCoreCommand 

### ISSUE THREAD

**Issue by aap-sc** [msteveb/jimtcl#300]
Hi!

I managed to build jimtcl with UBSan enabled (well, originally I've build OpenOCD that has jimtcl 0.82 integrated) and I observed some failures during tests. I've managed to compose a short reproduction for one of the failures.

Build:

```
CFLAGS="-fsanitize=undefined -Wl,-ldl" ./configure 
make
```

Run jimsh:

```
./jimsh
set l [list a b]
lreplace $l 0 0
```

UBSan will complain like this:

```
jim.c:7128:5: runtime error: null pointer passed as argument 1, which is declared to never be null
jim.c:7128:5: runtime error: null pointer passed as argument 2, which is declared to never be null
```

My understanding is that UBSan is correct here, since this corresponds to:

```
memmove(point + elemc, point, (currentLen - idx) * sizeof(Jim_Obj *));
```
statement when `point` is nullptr (I've checked with GDB). According to C language standard src/dst should not be NULL.

The NULL pointer comes from the following code segment:

```
static int Jim_LreplaceCoreCommand(Jim_Interp *interp, int argc, Jim_Obj *const *argv)
{
...
    /* Add the first set of elements */
    newListObj = Jim_NewListObj(interp, listObj->internalRep.listValue.ele, first);

    /* Add supplied elements */
/* HERE argv + 4 == NULL */   ListInsertElements(newListObj, -1, argc - 4, argv + 4); 

    /* Add the remaining elements */
    ListInsertElements(newListObj, -1, len - first - rangeLen, listObj->internalRep.listValue.ele + first + rangeLen);

    Jim_SetResult(interp, newListObj);
    return JIM_OK;
```

I guess that it would not hurt to fix the issue. To avoid the errors from sanitizers.

 If this is something worth fixing -  I can try and reproduce other issues.

**Comment by msteveb** [comment]
Thanks for the report. Fixed, plus a couple of others.
