### ISSUE TITLE
GCC 14: jimtcl will no longer build

### ISSUE THREAD

**Issue by andressbarajas** [msteveb/jimtcl#303]
-Wimplicit-function-declaration will be made into an error on GCC 14 when released:
https://github.com/gcc-mirror/gcc/commit/55e94561e97ed0bce4774aa1c6b5d5d82209a379

```
jim-file.c: In function ‘file_lstat’:
./jimiocompat.h:90:34: error: implicit declaration of function ‘lstat’; did you mean ‘stat’? [-Wimplicit-function-declaration]
   90 |             #define Jim_LinkStat lstat
      |                                  ^~~~~
jim-file.c:708:9: note: in expansion of macro ‘Jim_LinkStat’
  708 |     if (Jim_LinkStat(path, sb) == -1) {
      |         ^~~~~~~~~~~~
```

**Comment by msteveb** [comment]
What platform is this on?

**Comment by andressbarajas** [comment]
MacOS

**Comment by msteveb** [comment]
See branch kos-fixes. At least it compiles, but you will need to see if it is useful enough

**Comment by andressbarajas** [comment]
We figured out the issue.  Turns out we have to configure newlib (https://github.com/KallistiOS/KallistiOS/pull/530) to expose lstat.  Thank you for your time looking into the issue and sorry it was wasted because of an issue on our side.
