### ISSUE TITLE
segfault after Ctrl-C with data buffered in pipe

### ISSUE THREAD

**Issue by The-Markitecht** [msteveb/jimtcl#312]
in `0.82-134-gdcea42c`
```
Welcome to Jim version 0.84
. lassign [pipe] r w
. puts $r yes
. puts $w yes
. source fileName
Segmentation fault
```
What you can't see there, is that I pressed Ctrl-C between the final letter of `source` and the space.  That `fileName` is just the automatic parameter suggestion.  (**_LOVE_** those, by the way!)
This is 100% repeatable on my `Linux hostname 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux`
`jimsh` built with `gcc (Debian 12.1.0-8) 12.1.0` and whatever `libc` comes with it.
That seems to be the minimal case script.  Omitting anything eliminates the segfault on my system.

**Comment by msteveb** [comment]
Thanks. Fixed on master-next
