### ISSUE TITLE
regsub incompatibility vis a vis canonical tclsh

### ISSUE THREAD

**Issue by sgbeal** [msteveb/jimtcl#320]
JIM_VERSION 83 from autosetup 0.7.2:

i just stumbled over the following regsub incompatibility and will report it as a bug while also accepting that it might be as-designed:

```
$ ./jimsh 
Welcome to Jim version 0.83
. set path "\$ROOT/foo/bar"
$ROOT/foo/bar
. regsub {^\$ROOT\y} $path baz/ path
0
. puts $path
$ROOT/foo/bar

$ tclsh
% puts $tcl_version
8.6
% set path "\$ROOT/foo/bar"
$ROOT/foo/bar
% regsub {^\$ROOT\y} $path baz/ path
1
% puts $path
baz//foo/bar
```

This particular use case is easily replaced (as it were) with `string map`, so i've got a workaround.

**Comment by The-Markitecht** [comment]
`\y` for word boundaries seems to be unsupported, per `jimregexp.c:885`, assuming you compiled `jimsh` with jim re engine and not posix re engine.

However it does support word boundaries, as `\<` and `\>` or alternatively `\m` and `\M`.

So to get what you described I'd do something like:
```regsub {^\$ROOT\M} $path baz/ new; puts $new```
or 
```regsub {^\$ROOT\>} $path baz/ new; puts $new```
or
```regsub {^\$ROOT(\m|\M)} $path baz/ new; puts $new```
or
```regsub {^\$ROOT/} $path baz// new; puts $new```

I'm assuming you meant for that extra slash to be in the result.

And remember, the command you gave can't be tested more than once consecutively since it writes back to the variable holding the source text.

**Comment by sgbeal** [comment]
> assuming you compiled jimsh with jim re engine and not posix re engine.

Indeed. Here, jimsh0.c is compiled using only `-DHAVE_REALPATH` (so that `file normalize` works).

> I'm assuming you meant for that extra slash to be in the result.

Yes. That was just dummy input to minimally demonstrate the problem found in a much larger script (part of the sqlite3 build's code-generation process, which i'm in the process of porting to autosetup and JimTCL).

For our purposes a simple `string map` actually does the job, it just won't protect against broken inputs (which "shouldn't happen," right?) as well as the regex would. i figured i'd report it, though, in case either the `\y` omission was unintentional or it was a genuine bug.

**Comment by msteveb** [comment]
Correct. \y is not supported. Take a look at 'Supported constraint escapes' in the docs - https://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html#_jim_built_in_regular_expressions

**Comment by sgbeal** [comment]
> Correct. \y is not supported. Take a look at 'Supported constraint escapes' in the docs - https://jim.tcl.tk/fossil/doc/trunk/Tcl_shipped.html#_jim_built_in_regular_expressions

Possible doc bug: that page says:

> Jim Tcl does not support back references. e.g. `\1`

but we're using `\1` in a snippet here:

```tcl
set RELEASE [readfile $::autosetup(srcdir)/VERSION]
regsub {([0-9]*\.*[0-9]*).*} $RELEASE {\1} VERSION
define VERSION $VERSION
define RELEASE $RELEASE
msg-result "RELEASE = $RELEASE"
msg-result "VERSION = $VERSION"
```

which emits:

```
RELEASE = 3.47.0
VERSION = 3.47
```

that was just run on a system which doesn't have tclsh installed, so it's got to be coming from jimsh.

**Comment by msteveb** [comment]
I guess that doc is not quite clear. When it refers to back references, it means back references in the pattern, not in the substitution. "Backreferences match the same text as previously matched by a capturing group".
