### ISSUE TITLE
MSVC-incompatible empty structs

### ISSUE THREAD

**Issue by sgbeal** [msteveb/jimtcl#322]
We're getting reports in the sqlite project that folks with some versions of msvc cannot build jimsh0 due to `{ }` appearing at the end of some array-of-struct constructs:

```
$ grep -B 1 '\{ \}' *.c
<false positive snipped>
--
jimsh0.c-        JIM_DEF_SUBCMD("trimright", "string ?trimchars?", 1, 2),
jimsh0.c:        { }
--
jimsh0.c-        JIM_DEF_SUBCMD("update", "varName ?arg ...? script", 2, -1),
jimsh0.c:        { }
--
jimsh0.c-        JIM_DEF_SUBCMD("version", NULL, 0, 0),
jimsh0.c:        { }
```

In the canonical sources those appear as:

`{ /* null terminator */ }`

Though i cannot verify this, presumably replacing those with `{0,0,0,0,0,0}` or `JIM_DEF_SUBCMD(0,0,0,0)` would resolve this.

**Comment by msteveb** [comment]
Thanks for the report. It's hard to be sure of the correct fix without more details. What version of MSVC? Does this solve it?
```
{ NULL }
```

**Comment by msteveb** [comment]
You can try this branch: https://github.com/msteveb/jimtcl/tree/msvc-fix-322

**Comment by sgbeal** [comment]
i'm unfortunately unable to reproduce the warning locally but the user who reported it also reported that my attempt at a patch worked for him: simply replacing `{ }` with `JIM_DEF_SUBCMD(0,0,0,0)`.

The compiler against which the problem was reported:

`D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x86\cl.EXE`

Apparently, C99 and later require struct initializers to have at least one entry:

<https://stackoverflow.com/a/17589839>

with C23 and later allowing empty initializers.

My reading is that your `{NULL}` solution should be fine and i'll get that one checked in downstream.
