### ISSUE TITLE
jim.tcl.tk inactive due to the tcl.tk hijacking

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#43]
The domain tcl.tk has been hijacked. More details can be found [at Hacker News](https://news.ycombinator.com/item?id=10480729).

**Comment by msteveb** [comment]
Thanks. I'll see if I can get jim.tcl-lang.org set up in the short term.

**Comment by msteveb** [comment]
Yes, http://jim.tcl-lang.org/ is now up. I will update the various links in due course, but we can hope that tcl.tk comes back soon
