### ISSUE TITLE
Tests involving [exec program >> file] fail on MSYS2/MinGW-w64

### ISSUE THREAD

**Issue by dbohdan** [msteveb/jimtcl#59]
This is a separate issue for the bug I found in https://github.com/msteveb/jimtcl/pull/57.

>Each of the failed tests involves [exec] appending the output of a command to a file. E.g. (this is the MSYS2 shell),
>
>```
>$ ./jimsh.exe -e 'exec echo "First line" >> new.file' && cat new.file
>/usr/bin/echo: write error: Bad file descriptor
>```
>However, the `>` redirect works:
>
>```
>$ ./jimsh.exe -e 'exec echo "First line" > new.file' && cat new.file
>
>First line
>
>```

**Comment by msteveb** [comment]
I don't have the environment to be able to reproduce this error, so hopefully you or someone else can resolve it.

**Comment by dbohdan** [comment]
Right. I made this as a bookmark for myself and in hope someone else might notice.

**Comment by dbohdan** [comment]
The problem doesn't manifest when the Jim Tcl binary built with MinGW-w64 (`jimsh.exe`) executes plain Windows console programs like `cmd.exe`:
```
C:\msys32\home\User\jimtcl>jimsh.exe -e "exec cmd.exe /c echo hi >> hi.txt"


C:\msys32\home\User\jimtcl>type hi.txt
hi

```
This suggests the bug may be the result of a normal Windows binary (`jimsh.exe`) interacting with ones built specifically for the MSYS2 environment (`echo.exe`), meaning the scope of the bug is narrower than it seemed from the start. One thing to check now is if it is possible to reproduce it with programs other than Jim Tcl starting MSYS2 binaries, i.e., if the bug is at all specific to Jim Tcl.

**Comment by msteveb** [comment]
The windows code in jim-exec.c is derived in large part from Tcl 8.6
One of the few differences I notice in the create flags that are passed to CreateProcess(). Perhaps Jim needs DETACHED_PROCESS.

**Comment by msteveb** [comment]
I also notice that Tcl doesn't use FILE_APPEND_DATA. Instead after opening, it seeks to the end of the file with:

`SetFilePointer(handle, 0, NULL, FILE_END);`

**Comment by dbohdan** [comment]
Great find! Replacing `FILE_APPEND_DATA` with a call to `SetFilePointer` fixes all the append-related tests. (`DETACHED_PROCESS` didn't.) Now only [12.1](https://github.com/msteveb/jimtcl/blob/master/tests/exec.test#L345) remains. I would simply add a `unix` constraint to it.

PR: https://github.com/msteveb/jimtcl/pull/60.
