### ISSUE TITLE
dict replace unstable

### ISSUE THREAD

**Issue by evanhunter** [msteveb/jimtcl#69]
Hi Steve,

I have found that the --random-hash makes test dict2.test:4.1 fail randomly.
You can see it failing with these commands, which should just give an endless column of "a b c d"
`./configure` --random-hash && make
while true; do ./jimsh -e "dict replace {a b c d}"; done`

Instead of "a b c d", fairly often "c d a b" is returned.

Regards,
Evan

**Comment by msteveb** [comment]
Thanks. Test fixed to not assume stable ordering.
