### ISSUE TITLE
Building out-of-tree

### ISSUE THREAD

**Issue by evanhunter** [msteveb/jimtcl#71]
I have found that the following build sequence fails:

./configure && make
mkdir build2
cd build2
../configure && make

This appears to be due to VPATH confusing the make system and causing it to partially find jimsh.o in the in-tree source directory even when building out-of-tree.

Replacing the VPATH statement with the following seems to fix it:
vpath %.h ..
vpath %.c ..
vpath %.tcl ..

i.e. only search for sources in the source directory - not objects/libs

Regards,

Evan

**Comment by msteveb** [comment]
Isn't this true for almost any autoconf/automake-based project? I think the recommendation is: "Don't do that!". Currently we also support bsd make. Does this support vpath? I don't think so.
