### ISSUE TITLE
Compile error with C89 compiler

### ISSUE THREAD

**Issue by statusbits** [msteveb/jimtcl#92]
'
jim-tclprefix.c: In function `Jim_TclPrefixCoreCommand':
jim-tclprefix.c:163: parse error before `int'
jim-tclprefix.c:165: `i' undeclared (first use in this function)
jim-tclprefix.c:165: (Each undeclared identifier is reported only once
jim-tclprefix.c:165: for each function it appears in.)
jim-tclprefix.c:165: `listlen' undeclared (first use in this function)
make[1]: *** [jim-tclprefix.o] Error 1
'

Local variables 'i' and 'listen' are declared in the middle of the code block (C99-style) which results in compilation error with C89-only compiler.

**Comment by msteveb** [comment]
Thanks for the report. Fixed!

**Comment by statusbits** [comment]
Thank you!
